// お店のデータ置き場です。
// お店を増やしたいときは、下の { ... } を1つコピーして書き足すだけでOKです。
//
// 項目の説明:
//   id      : お店のURL用のID(半角の英小文字・数字・ハイフンだけ。お店ごとに違うものにする)。
//             詳細ページのURLは「?shop=このID」になります(例: ?shop=viet-nhat)。
//             ※ 公開したあとに変えると、そのURLでは開けなくなるので、いちど決めたら変えないでください。
//   name    : 店名
//   address : 住所
//   lat/lng : 緯度・経度(Google マップでお店を右クリックすると調べられます)
//   prefecture : 都道府県(「東京都」「神奈川県」など。下の prefectures の key と同じ文字にする)
//   area    : エリア(新宿・池袋・渋谷・上野など)。{ ja, en, vi } の形で書きます。
//             絞り込みボタンのエリアは、ここに書かれたものから自動で作られます。
//             新しいエリアを使うときは、お店の area に書くだけでOKです(ボタンが自動で増えます)。
//   dishes  : 取り扱い料理(複数書けます)。いまは、すべてのお店が ["ベトナム料理"] です。
//             使える名前は、下の dishTypes に書いたものです。絞り込みボタンの「料理」は、ここに書かれたものから自動で作られます。
//   image / imageSource / imageCredit : 店舗の画像(すべて省略してもOK)
//             image       : 画像のファイル名(例: "images/viet-nhat.jpg")。空、または省略すると、デフォルト画像が出ます。
//             imageSource : 画像の入手元・利用許可の記録(例: "店舗から提供", "自分で撮影")。画面には出ません。
//             imageCredit : 画像のクレジット表記(例: "撮影: 山田太郎")。書くと、画像の下に小さく表示されます。
//             ※ 利用の許可を確認できた画像だけを登録してください。
//               Google マップ・食べログ・Retty・Instagram などの画像を、許可なくコピーして使うことはできません。
//             例) image: "images/viet-nhat.jpg", imageSource: "店舗から提供", imageCredit: "写真提供: ○○店",
//   price   : 価格帯(省略してもOK。※ 今は、画面には表示していません。データだけ残しています)
//   hours   : 営業時間(省略してもOK。※ 今は、画面には表示していません。データだけ残しています)
//             どちらも、まだ調べていないお店は { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" } としています。
//   type    : お店の種類。"restaurant"(料理店) か "grocery"(食材店)。省略すると "restaurant" として扱います。
//             食材店は dishes(取り扱い料理)を書かなくてOKです。
//   category : カテゴリー(例: "ベトナム料理・居酒屋")。省略してもOK。詳細ページに出ます。英語・ベトナム語は categoryLabels に書きます。
//   closed  : 定休日(例: "水曜日")。{ ja, en, vi } でもOK。省略してもOK。※ 今は、画面には表示していません(データだけ残しています)。
//   feature : お店の特徴(省略してもOK。書いたお店だけ画面に表示されます)
//   googleMapsUrl : そのお店の Google マップのURL(省略してもOK)
//             Google マップでお店のページを開き、「共有」→「リンクをコピー」で取得できます。
//             例) googleMapsUrl: "https://maps.app.goo.gl/xxxxxxxx",
//             省略したお店は、店名と住所から Google マップの検索ページを自動で開きます。
//
// name / address / feature は、次の2通りの書き方ができます。
//   ・普通の文字列          → どの言語でも同じ文字を表示
//       feature: "Viet Nhat",
//   ・言語ごとの { ja, en, vi } → 選んだ言語の文字を表示
//       name: { ja: "ベトナム料理 ベトニャット", en: "Viet Nhat", vi: "Viet Nhat" },
//   { } の中で書いていない言語は、日本語(ja)で代わりに表示されます。
//
// ※ 取り扱い料理(dishes)は、お店のメニューを実際に確認できていないため、すべて「ベトナム料理」に統一しています。
// ※ 店名の日本語(ja)は、各店の公開情報(食べログ・ぐるなび・公式サイトなど)で確認した表記です。
// ※ 2つめ以降の地域(千代田区〜神奈川県・千葉県)の緯度・経度は、国土地理院の住所検索で調べた値です。
//   番地までの精度なので、ピンが建物から少しずれる場合があります(「1丁目」までの住所のお店は、
//   丁目の中心付近に立ちます)。正確な位置が分かるお店は、書き換えてください。
// ※ en(英語)と vi(ベトナム語)の住所は、日本語の住所をもとに機械的に
//   ローマ字表記にしたものです。正式な表記が分かるお店は、書き換えてください。

// 都道府県の絞り込みボタン(この並び順で表示されます)
//   key   : お店の prefecture に書く名前(下のお店データと同じ文字にしてください)
//   label : ボタンに出す文字
// 茨城・栃木・群馬などを増やしたいときは、ここに1行足すだけでOKです。
const prefectures = [
  { key: "東京都", label: { ja: "東京", en: "Tokyo", vi: "Tokyo" } },
  { key: "神奈川県", label: { ja: "神奈川", en: "Kanagawa", vi: "Kanagawa" } },
  { key: "千葉県", label: { ja: "千葉", en: "Chiba", vi: "Chiba" } },
  { key: "埼玉県", label: { ja: "埼玉", en: "Saitama", vi: "Saitama" } },
];

// 料理の分類(絞り込みボタンの並び順と、ボタンに出す文字)
//   key   : お店の dishes に書く名前(下のお店データと同じ文字にしてください)
//   label : ボタンに出す文字({ ja, en, vi })
// 絞り込みボタンは、お店の dishes に書かれた分類から自動で作られ、この一覧の順に並びます。
//
// ※ いまは、すべてのお店を「ベトナム料理」に統一しています。
//   フォー・バインミーなどの細かい取り扱い料理は、お店のメニューを確認できていないため、登録していません。
//   メニューを確認できたら、ここに分類(例: フォー・バインミー)を足して、お店の dishes に書けば、
//   絞り込みボタンが自動で増えます。
const dishTypes = [
  { key: "ベトナム料理", label: { ja: "ベトナム料理", en: "Vietnamese cuisine", vi: "Món Việt" } },
];

// カテゴリー(お店の category)の英語・ベトナム語の表示名。ここに無い category は、書いた文字のまま表示されます。
const categoryLabels = {
  "ベトナム料理": { en: "Vietnamese cuisine", vi: "Món Việt" },
  "ベトナム料理・居酒屋": { en: "Vietnamese cuisine / Izakaya", vi: "Món Việt / Quán nhậu" },
  "ベトナム料理・カフェ": { en: "Vietnamese cuisine / Cafe", vi: "Món Việt / Quán cà phê" },
  "ベトナム料理・軽食": { en: "Vietnamese cuisine / Light meals", vi: "Món Việt / Đồ ăn nhẹ" },
  "ベトナム料理・フォー": { en: "Vietnamese cuisine / Pho", vi: "Món Việt / Phở" },
  "ベトナム・アジア料理": { en: "Vietnamese & Asian cuisine", vi: "Món Việt & Á" },
  "フォー": { en: "Pho", vi: "Phở" },
  "フォー専門": { en: "Pho specialty", vi: "Chuyên phở" },
  "フォー・ベトナム料理": { en: "Pho / Vietnamese cuisine", vi: "Phở / Món Việt" },
  "バインミー": { en: "Banh mi", vi: "Bánh mì" },
  "バインミー・フォー": { en: "Banh mi / Pho", vi: "Bánh mì / Phở" },
  "惣菜・テイクアウト": { en: "Deli / Takeout", vi: "Món ăn sẵn / Mang đi" },
  "ベトナム食材店": { en: "Vietnamese grocery", vi: "Tạp hóa Việt" },
};

const restaurants = [
  // --- 新宿区 ---
  {
    id: "viet-nhat",
    name: {
      ja: "ベトナム料理 ベトニャット",
      en: "Viet Nhat",
      vi: "Viet Nhat",
    },
    address: {
      ja: "東京都新宿区西新宿1-31-3",
      en: "1-31-3 Nishi-Shinjuku, Shinjuku-ku, Tokyo",
      vi: "1-31-3 Nishi-Shinjuku, Quận Shinjuku, Tokyo",
    },
    lat: 35.6900589,
    lng: 139.712109,
    prefecture: "東京都",
    area: { ja: "新宿", en: "Shinjuku", vi: "Shinjuku" },
    dishes: ["ベトナム料理"],
  },
  {
    id: "hasunamu",
    name: {
      ja: "ベトナム料理専門店 ハスナム",
      en: "Hasunamu",
      vi: "Hasunamu",
    },
    address: {
      ja: "東京都新宿区歌舞伎町1-3-15",
      en: "1-3-15 Kabukicho, Shinjuku-ku, Tokyo",
      vi: "1-3-15 Kabukicho, Quận Shinjuku, Tokyo",
    },
    lat: 35.6945472,
    lng: 139.7038418,
    prefecture: "東京都",
    area: { ja: "新宿", en: "Shinjuku", vi: "Shinjuku" },
    dishes: ["ベトナム料理"],
  },
  {
    id: "pho-hanoi-yatai-33",
    name: {
      ja: "ベトナム料理 フォーハノイ屋台33 ルミネエスト新宿店",
      en: "Pho Hanoi Yatai 33",
      vi: "Pho Hanoi Yatai 33",
    },
    address: {
      ja: "東京都新宿区新宿3-38-1",
      en: "3-38-1 Shinjuku, Shinjuku-ku, Tokyo",
      vi: "3-38-1 Shinjuku, Quận Shinjuku, Tokyo",
    },
    lat: 35.6912132,
    lng: 139.701106,
    prefecture: "東京都",
    area: { ja: "新宿", en: "Shinjuku", vi: "Shinjuku" },
    dishes: ["ベトナム料理"],
  },

  // --- 渋谷区 ---
  {
    id: "hoang-ngan-shibuya",
    name: {
      ja: "ベトナム料理 ホァングン 渋谷文化村通り店",
      en: "Hoang Ngan Vietnamese Restaurant",
      vi: "Hoang Ngan Vietnamese Restaurant",
    },
    address: {
      ja: "東京都渋谷区道玄坂2-25-10",
      en: "2-25-10 Dogenzaka, Shibuya-ku, Tokyo",
      vi: "2-25-10 Dogenzaka, Quận Shibuya, Tokyo",
    },
    lat: 35.6602955,
    lng: 139.6971483,
    prefecture: "東京都",
    area: { ja: "渋谷", en: "Shibuya", vi: "Shibuya" },
    dishes: ["ベトナム料理"],
  },
  {
    id: "bagus-shibuya",
    name: {
      ja: "東南アジア屋台酒場 バグース",
      en: "Southeast Asian Izakaya Bagus",
      vi: "Southeast Asian Izakaya Bagus",
    },
    address: {
      ja: "東京都渋谷区道玄坂1-6-5",
      en: "1-6-5 Dogenzaka, Shibuya-ku, Tokyo",
      vi: "1-6-5 Dogenzaka, Quận Shibuya, Tokyo",
    },
    lat: 35.6577554,
    lng: 139.699176,
    prefecture: "東京都",
    area: { ja: "渋谷", en: "Shibuya", vi: "Shibuya" },
    dishes: ["ベトナム料理"],
  },
  {
    id: "an-di",
    name: {
      ja: "アンディ",
      en: "Ăn Đi",
      vi: "Ăn Đi",
    },
    address: {
      ja: "東京都渋谷区神宮前3-42-12",
      en: "3-42-12 Jingumae, Shibuya-ku, Tokyo",
      vi: "3-42-12 Jingumae, Quận Shibuya, Tokyo",
    },
    lat: 35.6719112,
    lng: 139.7138988,
    prefecture: "東京都",
    area: { ja: "渋谷", en: "Shibuya", vi: "Shibuya" },
    dishes: ["ベトナム料理"],
  },

  // --- 豊島区 ---
  {
    id: "hi-viet-nam-ikebukuro",
    name: {
      ja: "Hi Viet Nam 池袋",
      en: "Hi Viet Nam 池袋",
      vi: "Hi Viet Nam 池袋",
    },
    address: {
      ja: "東京都豊島区西池袋1-44-10",
      en: "1-44-10 Nishi-Ikebukuro, Toshima-ku, Tokyo",
      vi: "1-44-10 Nishi-Ikebukuro, Quận Toshima, Tokyo",
    },
    lat: 35.733006,
    lng: 139.7120602,
    prefecture: "東京都",
    area: { ja: "池袋", en: "Ikebukuro", vi: "Ikebukuro" },
    dishes: ["ベトナム料理"],
  },
  {
    id: "pho-viet",
    name: {
      ja: "フォーベト レストラン",
      en: "Pho Viet",
      vi: "Pho Viet",
    },
    address: {
      ja: "東京都豊島区西池袋3-31-15",
      en: "3-31-15 Nishi-Ikebukuro, Toshima-ku, Tokyo",
      vi: "3-31-15 Nishi-Ikebukuro, Quận Toshima, Tokyo",
    },
    lat: 35.7307282,
    lng: 139.7060359,
    prefecture: "東京都",
    area: { ja: "池袋", en: "Ikebukuro", vi: "Ikebukuro" },
    dishes: ["ベトナム料理"],
  },
  {
    id: "saigon-restaurant-ikebukuro",
    name: {
      ja: "ベトナム料理 サイゴンレストラン 池袋東口",
      en: "Saigon Restaurant",
      vi: "Saigon Restaurant",
    },
    address: {
      ja: "東京都豊島区東池袋1-7-10",
      en: "1-7-10 Higashi-Ikebukuro, Toshima-ku, Tokyo",
      vi: "1-7-10 Higashi-Ikebukuro, Quận Toshima, Tokyo",
    },
    lat: 35.7315343,
    lng: 139.7140152,
    prefecture: "東京都",
    area: { ja: "池袋", en: "Ikebukuro", vi: "Ikebukuro" },
    dishes: ["ベトナム料理"],
  },
  {
    id: "pho-thin-tokyo",
    name: {
      ja: "フォーティントーキョー",
      en: "Phở Thìn Tokyo",
      vi: "Phở Thìn Tokyo",
    },
    address: {
      ja: "東京都豊島区東池袋1-12-14",
      en: "1-12-14 Higashi-Ikebukuro, Toshima-ku, Tokyo",
      vi: "1-12-14 Higashi-Ikebukuro, Quận Toshima, Tokyo",
    },
    lat: 35.7294032,
    lng: 139.7146096,
    prefecture: "東京都",
    area: { ja: "池袋", en: "Ikebukuro", vi: "Ikebukuro" },
    dishes: ["ベトナム料理"],
  },

  // --- 台東区 ---
  {
    id: "la-viet-ueno",
    name: {
      ja: "ラヴェト",
      en: "La Việt",
      vi: "La Việt",
    },
    address: {
      ja: "東京都台東区東上野4-10-7",
      en: "4-10-7 Higashi-Ueno, Taito-ku, Tokyo",
      vi: "4-10-7 Higashi-Ueno, Quận Taito, Tokyo",
    },
    lat: 35.7141336,
    lng: 139.7798082,
    prefecture: "東京都",
    area: { ja: "上野", en: "Ueno", vi: "Ueno" },
    dishes: ["ベトナム料理"],
  },
  {
    id: "tay-ho-quan",
    name: {
      ja: "ベトナム料理 テイホークァン",
      en: "Tay Ho Quan",
      vi: "Tay Ho Quan",
    },
    address: {
      ja: "東京都台東区上野2-12-15",
      en: "2-12-15 Ueno, Taito-ku, Tokyo",
      vi: "2-12-15 Ueno, Quận Taito, Tokyo",
    },
    lat: 35.7094776,
    lng: 139.7717179,
    prefecture: "東京都",
    area: { ja: "上野", en: "Ueno", vi: "Ueno" },
    dishes: ["ベトナム料理"],
  },
  {
    id: "pho-yen-95",
    name: {
      ja: "フォーエン95",
      en: "Phở Yên 95",
      vi: "Phở Yên 95",
    },
    address: {
      ja: "東京都台東区池之端1-1-1",
      en: "1-1-1 Ikenohata, Taito-ku, Tokyo",
      vi: "1-1-1 Ikenohata, Quận Taito, Tokyo",
    },
    lat: 35.7089252,
    lng: 139.769584,
    prefecture: "東京都",
    area: { ja: "上野", en: "Ueno", vi: "Ueno" },
    dishes: ["ベトナム料理"],
  },

  // --- 千代田区・その他の東京都 ---
  {
    id: "beto-ya-jimbocho",
    name: "ベト屋 神保町店",
    address: {
      ja: "東京都千代田区神田神保町1-19-3 1F",
      en: "1F, 1-19-3 Kanda-Jimbocho, Chiyoda-ku, Tokyo",
      vi: "1F, 1-19-3 Kanda-Jimbocho, Quận Chiyoda, Tokyo",
    },
    lat: 35.6952630,
    lng: 139.7604680,
    prefecture: "東京都",
    area: { ja: "神保町", en: "Jimbocho", vi: "Jimbocho" },
    dishes: ["ベトナム料理"],
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=%E3%83%99%E3%83%88%E5%B1%8B%E7%A5%9E%E4%BF%9D%E7%94%BA%E5%BA%97+%E6%9D%B1%E4%BA%AC%E9%83%BD%E5%8D%83%E4%BB%A3%E7%94%B0%E5%8C%BA%E7%A5%9E%E7%94%B0%E7%A5%9E%E4%BF%9D%E7%94%BA1-19-3",
  },
  {
    id: "banh-xeo-saigon-yurakucho",
    name: "バインセオ サイゴン",
    address: {
      ja: "東京都千代田区有楽町2-7-1",
      en: "2-7-1 Yurakucho, Chiyoda-ku, Tokyo",
      vi: "2-7-1 Yurakucho, Quận Chiyoda, Tokyo",
    },
    lat: 35.6742130,
    lng: 139.7636570,
    prefecture: "東京都",
    area: { ja: "有楽町", en: "Yurakucho", vi: "Yurakucho" },
    dishes: ["ベトナム料理"],
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=%E3%83%90%E3%82%A4%E3%83%B3%E3%82%BB%E3%82%AA%E3%82%B5%E3%82%A4%E3%82%B4%E3%83%B3+%E6%9D%B1%E4%BA%AC%E9%83%BD%E5%8D%83%E4%BB%A3%E7%94%B0%E5%8C%BA%E6%9C%89%E6%A5%BD%E7%94%BA2-7-1",
  },
  {
    id: "vietnamese-cyclo-hibiya",
    name: "ベトナミーズ・シクロ 東京ミッドタウン日比谷",
    address: {
      ja: "東京都千代田区有楽町1-1-2",
      en: "1-1-2 Yurakucho, Chiyoda-ku, Tokyo",
      vi: "1-1-2 Yurakucho, Quận Chiyoda, Tokyo",
    },
    lat: 35.6740880,
    lng: 139.7595520,
    prefecture: "東京都",
    area: { ja: "日比谷", en: "Hibiya", vi: "Hibiya" },
    dishes: ["ベトナム料理"],
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=%E3%83%99%E3%83%88%E3%83%8A%E3%83%9F%E3%83%BC%E3%82%BA%E3%82%B7%E3%82%AF%E3%83%AD%E6%9D%B1%E4%BA%AC%E3%83%9F%E3%83%83%E3%83%89%E3%82%BF%E3%82%A6%E3%83%B3%E6%97%A5%E6%AF%94%E8%B0%B7",
  },
  {
    id: "chopsticks-koenji",
    name: "チョップスティックス",
    address: {
      ja: "東京都杉並区高円寺北3-22-8",
      en: "3-22-8 Koenji-kita, Suginami-ku, Tokyo",
      vi: "3-22-8 Koenji-kita, Quận Suginami, Tokyo",
    },
    lat: 35.7059940,
    lng: 139.6488490,
    prefecture: "東京都",
    area: { ja: "高円寺", en: "Koenji", vi: "Koenji" },
    dishes: ["ベトナム料理"],
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=%E3%83%81%E3%83%A7%E3%83%83%E3%83%97%E3%82%B9%E3%83%86%E3%82%A3%E3%83%83%E3%82%AF%E3%82%B9+%E6%9D%B1%E4%BA%AC%E9%83%BD%E6%9D%89%E4%B8%A6%E5%8C%BA%E9%AB%98%E5%86%86%E5%AF%BA%E5%8C%973-22-8",
  },
  {
    id: "hanoi-no-hoi-san",
    name: "ハノイのホイさん",
    address: {
      ja: "東京都渋谷区桜丘町17-6",
      en: "17-6 Sakuragaokacho, Shibuya-ku, Tokyo",
      vi: "17-6 Sakuragaokacho, Quận Shibuya, Tokyo",
    },
    lat: 35.6561550,
    lng: 139.7008210,
    prefecture: "東京都",
    area: { ja: "渋谷", en: "Shibuya", vi: "Shibuya" },
    dishes: ["ベトナム料理"],
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=%E3%83%8F%E3%83%8E%E3%82%A4%E3%81%AE%E3%83%9B%E3%82%A4%E3%81%95%E3%82%93+%E6%9D%B1%E4%BA%AC%E9%83%BD%E6%B8%8B%E8%B0%B7%E5%8C%BA%E6%A1%9C%E4%B8%98%E7%94%BA17-6",
  },
  {
    id: "saigon-majestic",
    name: "サイゴンマジェスティック",
    address: {
      ja: "東京都墨田区錦糸3-3-9",
      en: "3-3-9 Kinshi, Sumida-ku, Tokyo",
      vi: "3-3-9 Kinshi, Quận Sumida, Tokyo",
    },
    lat: 35.6979030,
    lng: 139.8138580,
    prefecture: "東京都",
    area: { ja: "錦糸町", en: "Kinshicho", vi: "Kinshicho" },
    dishes: ["ベトナム料理"],
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=%E3%82%B5%E3%82%A4%E3%82%B4%E3%83%B3%E3%83%9E%E3%82%B8%E3%82%A7%E3%82%B9%E3%83%86%E3%82%A3%E3%83%83%E3%82%AF+%E6%9D%B1%E4%BA%AC%E9%83%BD%E5%A2%A8%E7%94%B0%E5%8C%BA%E9%8C%A6%E7%B3%B83-3-9",
  },
  {
    id: "ecoda-hem",
    name: "ECODA HEM",
    address: {
      ja: "東京都練馬区旭丘1-74-9",
      en: "1-74-9 Asahigaoka, Nerima-ku, Tokyo",
      vi: "1-74-9 Asahigaoka, Quận Nerima, Tokyo",
    },
    lat: 35.7365950,
    lng: 139.6725920,
    prefecture: "東京都",
    area: { ja: "江古田", en: "Ekoda", vi: "Ekoda" },
    dishes: ["ベトナム料理"],
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=ECODA+HEM+%E6%9D%B1%E4%BA%AC%E9%83%BD%E7%B7%B4%E9%A6%AC%E5%8C%BA%E6%97%AD%E4%B8%981-74-9",
  },
  {
    id: "bia-hoi-chop-nakano",
    name: "ビアホイチョップ",
    address: {
      ja: "東京都中野区中野5-53-1",
      en: "5-53-1 Nakano, Nakano-ku, Tokyo",
      vi: "5-53-1 Nakano, Quận Nakano, Tokyo",
    },
    lat: 35.7090110,
    lng: 139.6666870,
    prefecture: "東京都",
    area: { ja: "中野", en: "Nakano", vi: "Nakano" },
    dishes: ["ベトナム料理"],
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=%E3%83%93%E3%82%A2%E3%83%9B%E3%82%A4%E3%83%81%E3%83%A7%E3%83%83%E3%83%97+%E6%9D%B1%E4%BA%AC%E9%83%BD%E4%B8%AD%E9%87%8E%E5%8C%BA%E4%B8%AD%E9%87%8E5-53-1",
  },

  // --- 神奈川県 ---
  {
    id: "co-tam",
    name: "Cô Tâm",
    address: {
      ja: "神奈川県横浜市中区初音町3-62",
      en: "3-62 Hatsunecho, Naka-ku, Yokohama, Kanagawa",
      vi: "3-62 Hatsunecho, Quận Naka, Yokohama, Kanagawa",
    },
    lat: 35.4405980,
    lng: 139.6237950,
    prefecture: "神奈川県",
    area: { ja: "桜木町・野毛周辺", en: "Sakuragicho / Noge area", vi: "Sakuragicho / Noge area" },
    dishes: ["ベトナム料理"],
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=C%C3%B4+T%C3%A2m+%E7%A5%9E%E5%A5%88%E5%B7%9D%E7%9C%8C%E6%A8%AA%E6%B5%9C%E5%B8%82%E4%B8%AD%E5%8C%BA%E5%88%9D%E9%9F%B3%E7%94%BA3-62",
  },
  {
    id: "ha-noi-vietnam-no-shokutaku",
    name: "Ha Noi ベトナムの食卓",
    address: {
      ja: "神奈川県横浜市神奈川区西神奈川1-18-4",
      en: "1-18-4 Nishi-Kanagawa, Kanagawa-ku, Yokohama, Kanagawa",
      vi: "1-18-4 Nishi-Kanagawa, Quận Kanagawa, Yokohama, Kanagawa",
    },
    lat: 35.4810260,
    lng: 139.6317900,
    prefecture: "神奈川県",
    area: { ja: "東神奈川", en: "Higashi-Kanagawa", vi: "Higashi-Kanagawa" },
    dishes: ["ベトナム料理"],
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Ha+Noi+%E3%83%99%E3%83%88%E3%83%8A%E3%83%A0%E3%81%AE%E9%A3%9F%E5%8D%93+%E7%A5%9E%E5%A5%88%E5%B7%9D%E7%9C%8C%E6%A8%AA%E6%B5%9C%E5%B8%82%E7%A5%9E%E5%A5%88%E5%B7%9D%E5%8C%BA%E8%A5%BF%E7%A5%9E%E5%A5%88%E5%B7%9D1-18-4",
  },
  {
    id: "hoahoa-hiyoshi",
    name: "ホアホア",
    address: {
      ja: "神奈川県横浜市港北区日吉本町1-4-25",
      en: "1-4-25 Hiyoshihoncho, Kohoku-ku, Yokohama, Kanagawa",
      vi: "1-4-25 Hiyoshihoncho, Quận Kohoku, Yokohama, Kanagawa",
    },
    lat: 35.5542680,
    lng: 139.6454010,
    prefecture: "神奈川県",
    area: { ja: "日吉", en: "Hiyoshi", vi: "Hiyoshi" },
    dishes: ["ベトナム料理"],
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=%E3%83%9B%E3%82%A2%E3%83%9B%E3%82%A2+%E7%A5%9E%E5%A5%88%E5%B7%9D%E7%9C%8C%E6%A8%AA%E6%B5%9C%E5%B8%82%E6%B8%AF%E5%8C%97%E5%8C%BA%E6%97%A5%E5%90%89",
  },
  {
    id: "betelnut-yokohama",
    name: "ビートルナッツ タイベトナメーゼ ディムサム",
    address: {
      ja: "神奈川県横浜市西区南幸1丁目",
      en: "Minami-Saiwai 1-chome, Nishi-ku, Yokohama, Kanagawa",
      vi: "Minami-Saiwai 1-chome, Quận Nishi, Yokohama, Kanagawa",
    },
    lat: 35.4658130,
    lng: 139.6206210,
    prefecture: "神奈川県",
    area: { ja: "横浜駅", en: "Yokohama Station", vi: "Yokohama Station" },
    dishes: ["ベトナム料理"],
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=%E3%83%93%E3%83%BC%E3%83%88%E3%83%AB%E3%83%8A%E3%83%83%E3%83%84+%E3%82%BF%E3%82%A4%E3%83%99%E3%83%88%E3%83%8A%E3%83%A1%E3%83%BC%E3%82%BC%E3%83%87%E3%82%A3%E3%83%A0%E3%82%B5%E3%83%A0+%E6%A8%AA%E6%B5%9C",
  },

  // --- 埼玉県 ---
  {
    id: "pho-hanoi-soka",
    name: "フォーハノイ",
    address: {
      ja: "埼玉県草加市稲荷3-30-12",
      en: "3-30-12 Inari, Soka, Saitama",
      vi: "3-30-12 Inari, Soka, Saitama",
    },
    lat: 35.8301930,
    lng: 139.8251190,
    prefecture: "埼玉県",
    area: { ja: "草加", en: "Soka", vi: "Soka" },
    dishes: ["ベトナム料理"],
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=%E3%83%95%E3%82%A9%E3%83%BC%E3%83%8F%E3%83%8E%E3%82%A4+%E5%9F%BC%E7%8E%89%E7%9C%8C%E8%8D%89%E5%8A%A0%E5%B8%82%E7%A8%B2%E8%8D%B73-30-12",
  },
  {
    id: "huong-ly-omiya",
    name: "フォン・リ",
    address: {
      ja: "埼玉県さいたま市大宮区大門町1-14",
      en: "1-14 Daimoncho, Omiya-ku, Saitama, Saitama",
      vi: "1-14 Daimoncho, Quận Omiya, Saitama, Saitama",
    },
    lat: 35.9071120,
    lng: 139.6256260,
    prefecture: "埼玉県",
    area: { ja: "大宮", en: "Omiya", vi: "Omiya" },
    dishes: ["ベトナム料理"],
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=%E3%83%95%E3%82%A9%E3%83%B3%E3%83%AA+%E5%9F%BC%E7%8E%89%E7%9C%8C%E3%81%95%E3%81%84%E3%81%9F%E3%81%BE%E5%B8%82%E5%A4%A7%E5%AE%AE%E5%8C%BA%E5%A4%A7%E9%96%80%E7%94%BA1-14",
  },
  {
    id: "jasmine-palace-omiya",
    name: "ジャスミンパレス 大宮店",
    address: {
      ja: "埼玉県さいたま市大宮区桜木町1丁目",
      en: "Sakuragicho 1-chome, Omiya-ku, Saitama, Saitama",
      vi: "Sakuragicho 1-chome, Quận Omiya, Saitama, Saitama",
    },
    lat: 35.9039500,
    lng: 139.6211850,
    prefecture: "埼玉県",
    area: { ja: "大宮", en: "Omiya", vi: "Omiya" },
    dishes: ["ベトナム料理"],
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=%E3%82%B8%E3%83%A3%E3%82%B9%E3%83%9F%E3%83%B3%E3%83%91%E3%83%AC%E3%82%B9%E5%A4%A7%E5%AE%AE%E5%BA%97+%E5%9F%BC%E7%8E%89%E7%9C%8C%E3%81%95%E3%81%84%E3%81%9F%E3%81%BE%E5%B8%82%E5%A4%A7%E5%AE%AE%E5%8C%BA%E6%A1%9C%E6%9C%A8%E7%94%BA",
  },
  {
    id: "trang-quynh-kawagoe",
    name: "チャンクインベトナムレストラン",
    address: {
      ja: "埼玉県川越市脇田町18-10",
      en: "18-10 Wakitacho, Kawagoe, Saitama",
      vi: "18-10 Wakitacho, Kawagoe, Saitama",
    },
    lat: 35.9081760,
    lng: 139.4841920,
    prefecture: "埼玉県",
    area: { ja: "川越", en: "Kawagoe", vi: "Kawagoe" },
    dishes: ["ベトナム料理"],
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=%E3%83%81%E3%83%A3%E3%83%B3%E3%82%AF%E3%82%A4%E3%83%B3%E3%83%99%E3%83%88%E3%83%8A%E3%83%A0%E3%83%AC%E3%82%B9%E3%83%88%E3%83%A9%E3%83%B3+%E5%9F%BC%E7%8E%89%E7%9C%8C%E5%B7%9D%E8%B6%8A%E5%B8%82%E8%84%87%E7%94%B0%E7%94%BA18-10",
  },

  // --- 千葉県 ---
  {
    id: "kome-chan",
    name: "ベトナムレストランKOME CHAN",
    address: {
      ja: "千葉県千葉市中央区新千葉2-8-9",
      en: "2-8-9 Shin-Chiba, Chuo-ku, Chiba, Chiba",
      vi: "2-8-9 Shin-Chiba, Quận Chuo, Chiba, Chiba",
    },
    lat: 35.6143880,
    lng: 140.1090850,
    prefecture: "千葉県",
    area: { ja: "新千葉", en: "Shin-Chiba", vi: "Shin-Chiba" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理",
  },
  {
    id: "jasmine-palace-chiba-sogo",
    name: "ジャスミンパレス 千葉そごう店",
    address: {
      ja: "千葉県千葉市中央区新町1000 そごう千葉店10F",
      en: "Sogo Chiba 10F, 1000 Shinmachi, Chuo-ku, Chiba, Chiba",
      vi: "Sogo Chiba 10F, 1000 Shinmachi, Quận Chuo, Chiba, Chiba",
    },
    lat: 35.6111180,
    lng: 140.1135710,
    prefecture: "千葉県",
    area: { ja: "千葉駅", en: "Chiba Station", vi: "Chiba Station" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理",
  },
  {
    id: "pho-chien",
    name: "Phở Chiến ベトナムフォー専門店",
    address: {
      ja: "千葉県千葉市中央区長洲1-29-10 IZUMI 2F",
      en: "IZUMI 2F, 1-29-10 Nagasu, Chuo-ku, Chiba, Chiba",
      vi: "IZUMI 2F, 1-29-10 Nagasu, Quận Chuo, Chiba, Chiba",
    },
    lat: 35.6017270,
    lng: 140.1209720,
    prefecture: "千葉県",
    area: { ja: "本千葉・長洲", en: "Hon-Chiba / Nagasu", vi: "Hon-Chiba / Nagasu" },
    dishes: ["ベトナム料理"],
    category: "フォー専門",
  },
  {
    id: "banh-mi-mochi",
    name: "バインミーモチ",
    address: {
      ja: "千葉県千葉市中央区弁天2-8-2",
      en: "2-8-2 Benten, Chuo-ku, Chiba, Chiba",
      vi: "2-8-2 Benten, Quận Chuo, Chiba, Chiba",
    },
    lat: 35.6159740,
    lng: 140.1149750,
    prefecture: "千葉県",
    area: { ja: "千葉・弁天", en: "Chiba / Benten", vi: "Chiba / Benten" },
    dishes: ["ベトナム料理"],
    category: "バインミー",
  },
  {
    id: "min-min-milk-tea-food",
    name: "Min-Min Milk Tea & Food",
    address: {
      ja: "千葉県千葉市中央区登戸1-1-17",
      en: "1-1-17 Nobuto, Chuo-ku, Chiba, Chiba",
      vi: "1-1-17 Nobuto, Quận Chuo, Chiba, Chiba",
    },
    lat: 35.6098560,
    lng: 140.1105960,
    prefecture: "千葉県",
    area: { ja: "千葉・登戸", en: "Chiba / Nobuto", vi: "Chiba / Nobuto" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理・軽食",
  },
  {
    id: "vietnam-kitchen-sogo-chiba",
    name: "ベトナムキッチン by ベト屋 そごう千葉店",
    address: {
      ja: "千葉県千葉市中央区新町1000 そごう千葉店B1",
      en: "Sogo Chiba B1, 1000 Shinmachi, Chuo-ku, Chiba, Chiba",
      vi: "Sogo Chiba B1, 1000 Shinmachi, Quận Chuo, Chiba, Chiba",
    },
    lat: 35.6111180,
    lng: 140.1135710,
    prefecture: "千葉県",
    area: { ja: "千葉駅", en: "Chiba Station", vi: "Chiba Station" },
    dishes: ["ベトナム料理"],
    category: "惣菜・テイクアウト",
  },
  {
    id: "vietnam-palace-funabashi",
    name: "VIETNAM PALACE 船橋",
    address: {
      ja: "千葉県船橋市本町4-40-1 レオセントラルスクエア3F",
      en: "Leo Central Square 3F, 4-40-1 Honcho, Funabashi, Chiba",
      vi: "Leo Central Square 3F, 4-40-1 Honcho, Funabashi, Chiba",
    },
    lat: 35.6990050,
    lng: 139.9868010,
    prefecture: "千葉県",
    area: { ja: "船橋駅", en: "Funabashi Station", vi: "Funabashi Station" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理",
  },
  {
    id: "sen-funabashi",
    name: "ベトナム料理SEN",
    address: {
      ja: "千葉県船橋市本町2-26-25",
      en: "2-26-25 Honcho, Funabashi, Chiba",
      vi: "2-26-25 Honcho, Funabashi, Chiba",
    },
    lat: 35.6986430,
    lng: 139.9833830,
    prefecture: "千葉県",
    area: { ja: "船橋駅", en: "Funabashi Station", vi: "Funabashi Station" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理",
  },
  {
    id: "banh-mi-ngonngon-funabashi",
    name: "バインミーゴンゴン 船橋店",
    address: {
      ja: "千葉県船橋市本町4-4-12",
      en: "4-4-12 Honcho, Funabashi, Chiba",
      vi: "4-4-12 Honcho, Funabashi, Chiba",
    },
    lat: 35.7011680,
    lng: 139.9882350,
    prefecture: "千葉県",
    area: { ja: "船橋駅", en: "Funabashi Station", vi: "Funabashi Station" },
    dishes: ["ベトナム料理"],
    category: "バインミー・フォー",
  },
  {
    id: "ao-dai-nishifunabashi",
    name: "アオザイレストラン 西船橋",
    address: {
      ja: "千葉県船橋市西船4-16-1 2F",
      en: "2F, 4-16-1 Nishifuna, Funabashi, Chiba",
      vi: "2F, 4-16-1 Nishifuna, Funabashi, Chiba",
    },
    lat: 35.7104720,
    lng: 139.9590450,
    prefecture: "千葉県",
    area: { ja: "西船橋", en: "Nishi-Funabashi", vi: "Nishi-Funabashi" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理",
  },
  {
    id: "bom-quan",
    name: "ボム・クアン",
    address: {
      ja: "千葉県船橋市湊町2-4-5 102",
      en: "Room 102, 2-4-5 Minatocho, Funabashi, Chiba",
      vi: "Room 102, 2-4-5 Minatocho, Funabashi, Chiba",
    },
    lat: 35.6948360,
    lng: 139.9832150,
    prefecture: "千葉県",
    area: { ja: "船橋・湊町", en: "Funabashi / Minatocho", vi: "Funabashi / Minatocho" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理",
  },
  {
    id: "ha-noi-pho-kitanarashino",
    name: "ハノイフォー PHỞ HÀ NỘI",
    address: {
      ja: "千葉県船橋市習志野台2-72-17",
      en: "2-72-17 Narashinodai, Funabashi, Chiba",
      vi: "2-72-17 Narashinodai, Funabashi, Chiba",
    },
    lat: 35.7237660,
    lng: 140.0486450,
    prefecture: "千葉県",
    area: { ja: "北習志野", en: "Kita-Narashino", vi: "Kita-Narashino" },
    dishes: ["ベトナム料理"],
    category: "フォー・ベトナム料理",
  },
  {
    id: "mattroi-shimosa-nakayama",
    name: "ベトナム&アジアンレストラン マッチョイ",
    address: {
      ja: "千葉県船橋市本中山2-22-9",
      en: "2-22-9 Honnakayama, Funabashi, Chiba",
      vi: "2-22-9 Honnakayama, Funabashi, Chiba",
    },
    lat: 35.7151340,
    lng: 139.9425510,
    prefecture: "千葉県",
    area: { ja: "下総中山", en: "Shimosa-Nakayama", vi: "Shimosa-Nakayama" },
    dishes: ["ベトナム料理"],
    category: "ベトナム・アジア料理",
  },
  {
    id: "thuys-kitchen",
    name: "Thuy's Kitchen",
    address: {
      ja: "千葉県船橋市坪井東2-15-3",
      en: "2-15-3 Tsuboi-Higashi, Funabashi, Chiba",
      vi: "2-15-3 Tsuboi-Higashi, Funabashi, Chiba",
    },
    lat: 35.7315600,
    lng: 140.0610350,
    prefecture: "千葉県",
    area: { ja: "坪井東", en: "Tsuboi-Higashi", vi: "Tsuboi-Higashi" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理",
  },
  {
    id: "pho-ngon-tsudanuma",
    name: "ベトナム料理フォーゴン",
    address: {
      ja: "千葉県習志野市谷津1-12-5 新津田沼ビル2F",
      en: "Shin-Tsudanuma Bldg 2F, 1-12-5 Yatsu, Narashino, Chiba",
      vi: "Shin-Tsudanuma Bldg 2F, 1-12-5 Yatsu, Narashino, Chiba",
    },
    lat: 35.6885680,
    lng: 140.0173650,
    prefecture: "千葉県",
    area: { ja: "津田沼・谷津", en: "Tsudanuma / Yatsu", vi: "Tsudanuma / Yatsu" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理",
  },
  {
    id: "ume-shin-matsudo",
    name: "UME ベトナム料理",
    address: {
      ja: "千葉県松戸市新松戸1-450-1",
      en: "1-450-1 Shin-Matsudo, Matsudo, Chiba",
      vi: "1-450-1 Shin-Matsudo, Matsudo, Chiba",
    },
    lat: 35.8282240,
    lng: 139.9200440,
    prefecture: "千葉県",
    area: { ja: "新松戸", en: "Shin-Matsudo", vi: "Shin-Matsudo" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理",
  },
  {
    id: "sai-gon-247",
    name: "SAI GON 247",
    address: {
      ja: "千葉県松戸市新松戸3-247",
      en: "3-247 Shin-Matsudo, Matsudo, Chiba",
      vi: "3-247 Shin-Matsudo, Matsudo, Chiba",
    },
    lat: 35.8224260,
    lng: 139.9181370,
    prefecture: "千葉県",
    area: { ja: "新松戸", en: "Shin-Matsudo", vi: "Shin-Matsudo" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理",
  },
  {
    id: "son-sen-shin-matsudo",
    name: "NHÀ HÀNG SƠN SEN (ソンセン レストラン)",
    address: {
      ja: "千葉県松戸市新松戸1-217",
      en: "1-217 Shin-Matsudo, Matsudo, Chiba",
      vi: "1-217 Shin-Matsudo, Matsudo, Chiba",
    },
    lat: 35.8296810,
    lng: 139.9204560,
    prefecture: "千葉県",
    area: { ja: "新松戸", en: "Shin-Matsudo", vi: "Shin-Matsudo" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理",
  },
  {
    id: "ha-thanh-kitchen-kitakogane",
    name: "ハータインキッチン",
    address: {
      ja: "千葉県松戸市小金2 ピコティ北小金西館109号",
      en: "Picoty Kita-Kogane West Bldg, Room 109, 2 Kogane, Matsudo, Chiba",
      vi: "Picoty Kita-Kogane West Bldg, Room 109, 2 Kogane, Matsudo, Chiba",
    },
    lat: 35.8323550,
    lng: 139.9311370,
    prefecture: "千葉県",
    area: { ja: "北小金", en: "Kita-Kogane", vi: "Kita-Kogane" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理",
  },
  {
    id: "himawari-shin-matsudo",
    name: "ベトナム料理ひまわり 新松戸店",
    address: {
      ja: "千葉県松戸市新松戸1-364 2F",
      en: "2F, 1-364 Shin-Matsudo, Matsudo, Chiba",
      vi: "2F, 1-364 Shin-Matsudo, Matsudo, Chiba",
    },
    lat: 35.8271140,
    lng: 139.9209290,
    prefecture: "千葉県",
    area: { ja: "新松戸", en: "Shin-Matsudo", vi: "Shin-Matsudo" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理",
  },
  {
    id: "little-vietnam-shin-matsudo",
    name: "リトルベトナム",
    address: {
      ja: "千葉県松戸市新松戸1-367-1",
      en: "1-367-1 Shin-Matsudo, Matsudo, Chiba",
      vi: "1-367-1 Shin-Matsudo, Matsudo, Chiba",
    },
    lat: 35.8271140,
    lng: 139.9209290,
    prefecture: "千葉県",
    area: { ja: "新松戸", en: "Shin-Matsudo", vi: "Shin-Matsudo" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理",
  },
  {
    id: "banh-mi-ngonngon-shin-matsudo",
    name: "バインミーゴンゴン 新松戸店",
    address: {
      ja: "千葉県松戸市新松戸2-35-1",
      en: "2-35-1 Shin-Matsudo, Matsudo, Chiba",
      vi: "2-35-1 Shin-Matsudo, Matsudo, Chiba",
    },
    lat: 35.8234060,
    lng: 139.9198910,
    prefecture: "千葉県",
    area: { ja: "新松戸", en: "Shin-Matsudo", vi: "Shin-Matsudo" },
    dishes: ["ベトナム料理"],
    category: "バインミー",
  },
  {
    id: "banh-mi-xin-chao-matsudo",
    name: "バインミーシンチャオ 松戸店",
    address: {
      ja: "千葉県松戸市松戸1149 イトーヨーカドー松戸店2F",
      en: "Ito-Yokado Matsudo 2F, 1149 Matsudo, Matsudo, Chiba",
      vi: "Ito-Yokado Matsudo 2F, 1149 Matsudo, Matsudo, Chiba",
    },
    lat: 35.7828940,
    lng: 139.9024960,
    prefecture: "千葉県",
    area: { ja: "松戸駅", en: "Matsudo Station", vi: "Matsudo Station" },
    dishes: ["ベトナム料理"],
    category: "バインミー",
  },
  {
    id: "viet-quan-kashiwa",
    name: "ベトナム料理 VIET QUAN柏店",
    address: {
      ja: "千葉県柏市柏2-8-15 B1F",
      en: "B1F, 2-8-15 Kashiwa, Kashiwa, Chiba",
      vi: "B1F, 2-8-15 Kashiwa, Kashiwa, Chiba",
    },
    lat: 35.8623810,
    lng: 139.9748230,
    prefecture: "千葉県",
    area: { ja: "柏駅", en: "Kashiwa Station", vi: "Kashiwa Station" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理",
  },
  {
    id: "pho-links-kashiwa",
    name: "フォーLINKS 柏店",
    address: {
      ja: "千葉県柏市柏4-4-8 1F",
      en: "1F, 4-4-8 Kashiwa, Kashiwa, Chiba",
      vi: "1F, 4-4-8 Kashiwa, Kashiwa, Chiba",
    },
    lat: 35.8632130,
    lng: 139.9743350,
    prefecture: "千葉県",
    area: { ja: "柏駅", en: "Kashiwa Station", vi: "Kashiwa Station" },
    dishes: ["ベトナム料理"],
    category: "フォー・ベトナム料理",
  },
  {
    id: "sunflower-motoyawata",
    name: "サンフラワー",
    address: {
      ja: "千葉県市川市八幡3-27-5",
      en: "3-27-5 Yawata, Ichikawa, Chiba",
      vi: "3-27-5 Yawata, Ichikawa, Chiba",
    },
    lat: 35.7239150,
    lng: 139.9282380,
    prefecture: "千葉県",
    area: { ja: "本八幡", en: "Motoyawata", vi: "Motoyawata" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理",
  },
  {
    id: "cal-viet-cintas365",
    name: "Cal－Viet CINTAS365",
    address: {
      ja: "千葉県市川市市川1-8-6 プレミアR9 1F",
      en: "Premier R9 1F, 1-8-6 Ichikawa, Ichikawa, Chiba",
      vi: "Premier R9 1F, 1-8-6 Ichikawa, Ichikawa, Chiba",
    },
    lat: 35.7298930,
    lng: 139.9068300,
    prefecture: "千葉県",
    area: { ja: "市川駅", en: "Ichikawa Station", vi: "Ichikawa Station" },
    dishes: ["ベトナム料理"],
    category: "ベトナム・アジア料理",
  },
  {
    id: "banh-mi-ngonngon-yachiyodai",
    name: "バインミーゴンゴン 八千代台店",
    address: {
      ja: "千葉県八千代市八千代台東1-14-4",
      en: "1-14-4 Yachiyodai-Higashi, Yachiyo, Chiba",
      vi: "1-14-4 Yachiyodai-Higashi, Yachiyo, Chiba",
    },
    lat: 35.7013470,
    lng: 140.0912930,
    prefecture: "千葉県",
    area: { ja: "八千代台", en: "Yachiyodai", vi: "Yachiyodai" },
    dishes: ["ベトナム料理"],
    category: "バインミー・フォー",
  },
  {
    id: "ngon-quan-yachiyodai",
    name: "ゴン クアン ベトナムレストラン",
    address: {
      ja: "千葉県八千代市八千代台南1-1-7",
      en: "1-1-7 Yachiyodai-Minami, Yachiyo, Chiba",
      vi: "1-1-7 Yachiyodai-Minami, Yachiyo, Chiba",
    },
    lat: 35.7002030,
    lng: 140.0899660,
    prefecture: "千葉県",
    area: { ja: "八千代台", en: "Yachiyodai", vi: "Yachiyodai" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理",
  },
  {
    id: "fill-quan",
    name: "FILL QUAN",
    address: {
      ja: "千葉県八千代市勝田台1-26-25 2F",
      en: "2F, 1-26-25 Katsutadai, Yachiyo, Chiba",
      vi: "2F, 1-26-25 Katsutadai, Yachiyo, Chiba",
    },
    lat: 35.7134280,
    lng: 140.1255950,
    prefecture: "千葉県",
    area: { ja: "勝田台", en: "Katsutadai", vi: "Katsutadai" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理",
  },
  {
    id: "pho-chan-katsutadai",
    name: "フォーちゃん",
    address: {
      ja: "千葉県八千代市勝田台1-13-34 1F",
      en: "1F, 1-13-34 Katsutadai, Yachiyo, Chiba",
      vi: "1F, 1-13-34 Katsutadai, Yachiyo, Chiba",
    },
    lat: 35.7146070,
    lng: 140.1277160,
    prefecture: "千葉県",
    area: { ja: "勝田台", en: "Katsutadai", vi: "Katsutadai" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理",
  },
  {
    id: "sen-vang-katsutadai",
    name: "SEN VANG",
    address: {
      ja: "千葉県八千代市勝田台1-14-71",
      en: "1-14-71 Katsutadai, Yachiyo, Chiba",
      vi: "1-14-71 Katsutadai, Yachiyo, Chiba",
    },
    lat: 35.7142980,
    lng: 140.1278690,
    prefecture: "千葉県",
    area: { ja: "勝田台", en: "Katsutadai", vi: "Katsutadai" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理",
  },
  {
    id: "fon-bun-ban-katsutadai",
    name: "フォン ブン バン",
    address: {
      ja: "千葉県八千代市勝田台北1-20-1",
      en: "1-20-1 Katsutadai-Kita, Yachiyo, Chiba",
      vi: "1-20-1 Katsutadai-Kita, Yachiyo, Chiba",
    },
    lat: 35.7153170,
    lng: 140.1229710,
    prefecture: "千葉県",
    area: { ja: "勝田台", en: "Katsutadai", vi: "Katsutadai" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理",
  },
  {
    id: "kazoku-togane",
    name: "ベトナム料理かぞく",
    address: {
      ja: "千葉県東金市東金925-7",
      en: "925-7 Togane, Togane, Chiba",
      vi: "925-7 Togane, Togane, Chiba",
    },
    lat: 35.5630840,
    lng: 140.3678130,
    prefecture: "千葉県",
    area: { ja: "東金", en: "Togane", vi: "Togane" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理",
  },
  {
    id: "pho77-narita",
    name: "ベトナムフォー77成田店",
    address: {
      ja: "千葉県成田市土屋411-1",
      en: "411-1 Tsuchiya, Narita, Chiba",
      vi: "411-1 Tsuchiya, Narita, Chiba",
    },
    lat: 35.7903590,
    lng: 140.3247220,
    prefecture: "千葉県",
    area: { ja: "成田", en: "Narita", vi: "Narita" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理・フォー",
  },
  {
    id: "pho-habeto-yotsukaido",
    name: "フォーハベト",
    address: {
      ja: "千葉県四街道市鹿渡1016-11",
      en: "1016-11 Shikawatashi, Yotsukaido, Chiba",
      vi: "1016-11 Shikawatashi, Yotsukaido, Chiba",
    },
    lat: 35.6626930,
    lng: 140.1662900,
    prefecture: "千葉県",
    area: { ja: "四街道駅", en: "Yotsukaido Station", vi: "Yotsukaido Station" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理",
  },

  // --- 神奈川県(追加分) ---
  {
    id: "sen-kannai",
    name: "SEN 関内店",
    address: {
      ja: "神奈川県横浜市中区伊勢佐木町2-11-3",
      en: "2-11-3 Isezakicho, Naka-ku, Yokohama, Kanagawa",
      vi: "2-11-3 Isezakicho, Quận Naka, Yokohama, Kanagawa",
    },
    lat: 35.4436720,
    lng: 139.6315000,
    prefecture: "神奈川県",
    area: { ja: "関内・伊勢佐木町", en: "Kannai / Isezakicho", vi: "Kannai / Isezakicho" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理",
    price: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
    hours: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
  },
  {
    id: "huong-que-yokohama",
    name: "Hương Quê - Yokohama",
    address: {
      ja: "神奈川県横浜市中区福富町仲通4-4",
      en: "4-4 Fukutomicho-Nakadori, Naka-ku, Yokohama, Kanagawa",
      vi: "4-4 Fukutomicho-Nakadori, Quận Naka, Yokohama, Kanagawa",
    },
    lat: 35.4451600,
    lng: 139.6315000,
    prefecture: "神奈川県",
    area: { ja: "福富町", en: "Fukutomicho", vi: "Fukutomicho" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理",
    price: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
    hours: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
  },
  {
    id: "an-an-quan",
    name: "AN AN QUAN",
    address: {
      ja: "神奈川県横浜市中区福富町西通5-5",
      en: "5-5 Fukutomicho-Nishidori, Naka-ku, Yokohama, Kanagawa",
      vi: "5-5 Fukutomicho-Nishidori, Quận Naka, Yokohama, Kanagawa",
    },
    lat: 35.4457550,
    lng: 139.6311490,
    prefecture: "神奈川県",
    area: { ja: "福富町", en: "Fukutomicho", vi: "Fukutomicho" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理",
    price: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
    hours: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
  },
  {
    id: "pho-viet-quan-2",
    name: "PHỞ VIỆT QUÁN 2",
    address: {
      ja: "神奈川県横浜市中区宮川町3-79",
      en: "3-79 Miyagawacho, Naka-ku, Yokohama, Kanagawa",
      vi: "3-79 Miyagawacho, Quận Naka, Yokohama, Kanagawa",
    },
    lat: 35.4467960,
    lng: 139.6276860,
    prefecture: "神奈川県",
    area: { ja: "桜木町・野毛", en: "Sakuragicho / Noge", vi: "Sakuragicho / Noge" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理",
    price: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
    hours: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
  },
  {
    id: "cyclo-yokohama-sakuragicho",
    name: "ベトナム料理酒場 シクロ 横浜桜木町店",
    address: {
      ja: "神奈川県横浜市中区花咲町2-63",
      en: "2-63 Hanasakicho, Naka-ku, Yokohama, Kanagawa",
      vi: "2-63 Hanasakicho, Quận Naka, Yokohama, Kanagawa",
    },
    lat: 35.4497830,
    lng: 139.6298520,
    prefecture: "神奈川県",
    area: { ja: "桜木町", en: "Sakuragicho", vi: "Sakuragicho" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理・居酒屋",
    price: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
    hours: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
  },
  {
    id: "vietnam-smile-isezakicho",
    name: "ベトナムスマイル",
    address: {
      ja: "神奈川県横浜市中区伊勢佐木町6-136",
      en: "6-136 Isezakicho, Naka-ku, Yokohama, Kanagawa",
      vi: "6-136 Isezakicho, Quận Naka, Yokohama, Kanagawa",
    },
    lat: 35.4394490,
    lng: 139.6261900,
    prefecture: "神奈川県",
    area: { ja: "伊勢佐木町", en: "Isezakicho", vi: "Isezakicho" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理",
    price: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
    hours: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
  },
  {
    id: "pho-minh-namamugi",
    name: "フォーミン",
    address: {
      ja: "神奈川県横浜市鶴見区岸谷1-24-3",
      en: "1-24-3 Kishiya, Tsurumi-ku, Yokohama, Kanagawa",
      vi: "1-24-3 Kishiya, Quận Tsurumi, Yokohama, Kanagawa",
    },
    lat: 35.4957050,
    lng: 139.6658330,
    prefecture: "神奈川県",
    area: { ja: "生麦", en: "Namamugi", vi: "Namamugi" },
    dishes: ["ベトナム料理"],
    category: "フォー・ベトナム料理",
    price: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
    hours: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
  },
  {
    id: "pho-89-tsunashima",
    name: "ベトナム料理PHO 89綱島店",
    address: {
      ja: "神奈川県横浜市港北区綱島西1-9-8",
      en: "1-9-8 Tsunashima-Nishi, Kohoku-ku, Yokohama, Kanagawa",
      vi: "1-9-8 Tsunashima-Nishi, Quận Kohoku, Yokohama, Kanagawa",
    },
    lat: 35.5366440,
    lng: 139.6329190,
    prefecture: "神奈川県",
    area: { ja: "綱島", en: "Tsunashima", vi: "Tsunashima" },
    dishes: ["ベトナム料理"],
    category: "フォー・ベトナム料理",
    price: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
    hours: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
  },
  {
    id: "tran-kitchen-hiyoshi",
    name: "Tran Kitchen 日吉店",
    address: {
      ja: "神奈川県横浜市港北区日吉本町1-1-10",
      en: "1-1-10 Hiyoshihoncho, Kohoku-ku, Yokohama, Kanagawa",
      vi: "1-1-10 Hiyoshihoncho, Quận Kohoku, Yokohama, Kanagawa",
    },
    lat: 35.5537190,
    lng: 139.6464390,
    prefecture: "神奈川県",
    area: { ja: "日吉", en: "Hiyoshi", vi: "Hiyoshi" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理",
    price: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
    hours: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
  },
  {
    id: "wins-hakuraku",
    name: "Win's(ベトナム＆アジアンカフェ WINS)",
    address: {
      ja: "神奈川県横浜市神奈川区六角橋1-4-6",
      en: "1-4-6 Rokkakubashi, Kanagawa-ku, Yokohama, Kanagawa",
      vi: "1-4-6 Rokkakubashi, Quận Kanagawa, Yokohama, Kanagawa",
    },
    lat: 35.4885290,
    lng: 139.6267850,
    prefecture: "神奈川県",
    area: { ja: "白楽・六角橋", en: "Hakuraku / Rokkakubashi", vi: "Hakuraku / Rokkakubashi" },
    dishes: ["ベトナム料理"],
    category: "ベトナム・アジア料理",
    price: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
    hours: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
  },
  {
    id: "hines-dining-hazawa",
    name: "ハインズダイニング 羽沢横浜国大店",
    address: {
      ja: "神奈川県横浜市神奈川区羽沢南2-44-44",
      en: "2-44-44 Hazawa-Minami, Kanagawa-ku, Yokohama, Kanagawa",
      vi: "2-44-44 Hazawa-Minami, Quận Kanagawa, Yokohama, Kanagawa",
    },
    lat: 35.4804190,
    lng: 139.5854340,
    prefecture: "神奈川県",
    area: { ja: "羽沢", en: "Hazawa", vi: "Hazawa" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理",
    price: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
    hours: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
  },
  {
    id: "banh-mi-cam-chan",
    name: "BANH MI CAMちゃん",
    address: {
      ja: "神奈川県横浜市南区高根町1-3-14",
      en: "1-3-14 Takanecho, Minami-ku, Yokohama, Kanagawa",
      vi: "1-3-14 Takanecho, Quận Minami, Yokohama, Kanagawa",
    },
    lat: 35.4378090,
    lng: 139.6273800,
    prefecture: "神奈川県",
    area: { ja: "阪東橋", en: "Bandobashi", vi: "Bandobashi" },
    dishes: ["ベトナム料理"],
    category: "バインミー",
    price: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
    hours: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
  },
  {
    id: "saigon-kim-thanh-kawasaki",
    name: "サイゴン キムタン 川崎本店",
    address: {
      ja: "神奈川県川崎市川崎区東田町4-7",
      en: "4-7 Higashidacho, Kawasaki-ku, Kawasaki, Kanagawa",
      vi: "4-7 Higashidacho, Quận Kawasaki, Kawasaki, Kanagawa",
    },
    lat: 35.5292090,
    lng: 139.7018590,
    prefecture: "神奈川県",
    area: { ja: "川崎駅・東田町", en: "Kawasaki Station / Higashidacho", vi: "Kawasaki Station / Higashidacho" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理",
    price: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
    hours: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
  },
  {
    id: "hanoi-restaurant-kawasaki",
    name: "Hanoi Restaurant Kawasaki",
    address: {
      ja: "神奈川県川崎市川崎区砂子2-6-11",
      en: "2-6-11 Isago, Kawasaki-ku, Kawasaki, Kanagawa",
      vi: "2-6-11 Isago, Quận Kawasaki, Kawasaki, Kanagawa",
    },
    lat: 35.5287250,
    lng: 139.7000120,
    prefecture: "神奈川県",
    area: { ja: "川崎駅", en: "Kawasaki Station", vi: "Kawasaki Station" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理",
    price: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
    hours: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
  },
  {
    id: "ngon-ngon-kawasaki",
    name: "NGON NGON",
    address: {
      ja: "神奈川県川崎市川崎区小川町4-1",
      en: "4-1 Ogawacho, Kawasaki-ku, Kawasaki, Kanagawa",
      vi: "4-1 Ogawacho, Quận Kawasaki, Kawasaki, Kanagawa",
    },
    lat: 35.5280720,
    lng: 139.6979680,
    prefecture: "神奈川県",
    area: { ja: "川崎駅", en: "Kawasaki Station", vi: "Kawasaki Station" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理",
    price: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
    hours: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
  },
  {
    id: "saigon-kyu-inadazutsumi",
    name: "Saigon 究",
    address: {
      ja: "神奈川県川崎市多摩区菅1-3-2",
      en: "1-3-2 Suge, Tama-ku, Kawasaki, Kanagawa",
      vi: "1-3-2 Suge, Quận Tama, Kawasaki, Kanagawa",
    },
    lat: 35.6324620,
    lng: 139.5350190,
    prefecture: "神奈川県",
    area: { ja: "稲田堤", en: "Inadazutsumi", vi: "Inadazutsumi" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理",
    price: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
    hours: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
  },
  {
    id: "cyclo-fujisawa-minamiguchi",
    name: "ベトナム料理酒場シクロ藤沢駅南口店",
    address: {
      ja: "神奈川県藤沢市鵠沼花沢町2-1",
      en: "2-1 Kugenuma-Hanazawacho, Fujisawa, Kanagawa",
      vi: "2-1 Kugenuma-Hanazawacho, Fujisawa, Kanagawa",
    },
    lat: 35.3377080,
    lng: 139.4857180,
    prefecture: "神奈川県",
    area: { ja: "藤沢駅", en: "Fujisawa Station", vi: "Fujisawa Station" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理・居酒屋",
    price: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
    hours: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
  },
  {
    id: "cyclo-honkugenuma",
    name: "ベトナム料理シクロ 鵠沼店",
    address: {
      ja: "神奈川県藤沢市本鵠沼3-12-30",
      en: "3-12-30 Hon-Kugenuma, Fujisawa, Kanagawa",
      vi: "3-12-30 Hon-Kugenuma, Fujisawa, Kanagawa",
    },
    lat: 35.3296050,
    lng: 139.4692230,
    prefecture: "神奈川県",
    area: { ja: "本鵠沼", en: "Hon-Kugenuma", vi: "Hon-Kugenuma" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理",
    price: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
    hours: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
  },
  {
    id: "le-mekong-fujisawa",
    name: "Le Mekong",
    address: {
      ja: "神奈川県藤沢市鵠沼石上1-3-14",
      en: "1-3-14 Kugenuma-Ishigami, Fujisawa, Kanagawa",
      vi: "1-3-14 Kugenuma-Ishigami, Fujisawa, Kanagawa",
    },
    lat: 35.3367120,
    lng: 139.4883420,
    prefecture: "神奈川県",
    area: { ja: "藤沢駅", en: "Fujisawa Station", vi: "Fujisawa Station" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理",
    price: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
    hours: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
  },
  {
    id: "pho-cat-tuong-kamakura",
    name: "Vietnam Pho Cát Tường(ベトナムフォー カットゥン)",
    address: {
      ja: "神奈川県鎌倉市小町2-11-27",
      en: "2-11-27 Komachi, Kamakura, Kanagawa",
      vi: "2-11-27 Komachi, Kamakura, Kanagawa",
    },
    lat: 35.3204610,
    lng: 139.5526580,
    prefecture: "神奈川県",
    area: { ja: "鎌倉駅・小町", en: "Kamakura Station / Komachi", vi: "Kamakura Station / Komachi" },
    dishes: ["ベトナム料理"],
    category: "フォー・ベトナム料理",
    price: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
    hours: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
  },
  {
    id: "pho-rascal-kamakura",
    name: "Pho Rascal",
    address: {
      ja: "神奈川県鎌倉市小町1-15",
      en: "1-15 Komachi, Kamakura, Kanagawa",
      vi: "1-15 Komachi, Kamakura, Kanagawa",
    },
    lat: 35.3164020,
    lng: 139.5515440,
    prefecture: "神奈川県",
    area: { ja: "鎌倉駅・小町", en: "Kamakura Station / Komachi", vi: "Kamakura Station / Komachi" },
    dishes: ["ベトナム料理"],
    category: "フォー・ベトナム料理",
    price: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
    hours: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
  },
  {
    id: "what-the-pho-yokosuka-chuo",
    name: "What the Phở Yokosuka Chuo",
    address: {
      ja: "神奈川県横須賀市本町1-8-2",
      en: "1-8-2 Honcho, Yokosuka, Kanagawa",
      vi: "1-8-2 Honcho, Yokosuka, Kanagawa",
    },
    lat: 35.2818450,
    lng: 139.6668400,
    prefecture: "神奈川県",
    area: { ja: "横須賀中央", en: "Yokosuka-Chuo", vi: "Yokosuka-Chuo" },
    dishes: ["ベトナム料理"],
    category: "フォー",
    price: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
    hours: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
  },
  {
    id: "bamboo-vietnam-kitchen-yokosuka",
    name: "バンブーベトナムキッチン",
    address: {
      ja: "神奈川県横須賀市大滝町1-24",
      en: "1-24 Otakicho, Yokosuka, Kanagawa",
      vi: "1-24 Otakicho, Yokosuka, Kanagawa",
    },
    lat: 35.2821040,
    lng: 139.6679380,
    prefecture: "神奈川県",
    area: { ja: "横須賀中央", en: "Yokosuka-Chuo", vi: "Yokosuka-Chuo" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理",
    price: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
    hours: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
  },
  {
    id: "alo-alo-yamato",
    name: "ベトナム料理カフェ aLo aLo",
    address: {
      ja: "神奈川県大和市大和南1-15-6",
      en: "1-15-6 Yamato-Minami, Yamato, Kanagawa",
      vi: "1-15-6 Yamato-Minami, Yamato, Kanagawa",
    },
    lat: 35.4694900,
    lng: 139.4660640,
    prefecture: "神奈川県",
    area: { ja: "大和駅", en: "Yamato Station", vi: "Yamato Station" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理・カフェ",
    price: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
    hours: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
  },
  {
    id: "quan-viet-kushitan-yamato",
    name: "Quan Viet 串たん",
    address: {
      ja: "神奈川県大和市大和東1-7-2",
      en: "1-7-2 Yamato-Higashi, Yamato, Kanagawa",
      vi: "1-7-2 Yamato-Higashi, Yamato, Kanagawa",
    },
    lat: 35.4703410,
    lng: 139.4629520,
    prefecture: "神奈川県",
    area: { ja: "大和駅", en: "Yamato Station", vi: "Yamato Station" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理・居酒屋",
    price: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
    hours: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
  },
  {
    id: "ohayo-odawara",
    name: "OHAYO ODAWARA",
    address: {
      ja: "神奈川県小田原市栄町2-9-7",
      en: "2-9-7 Sakaecho, Odawara, Kanagawa",
      vi: "2-9-7 Sakaecho, Odawara, Kanagawa",
    },
    lat: 35.2546080,
    lng: 139.1587070,
    prefecture: "神奈川県",
    area: { ja: "小田原駅", en: "Odawara Station", vi: "Odawara Station" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理",
    price: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
    hours: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
  },
  {
    id: "bamboo-vietnam-odawara",
    name: "Bamboo Vietnam バンブーベトナム",
    address: {
      ja: "神奈川県小田原市荻窪314",
      en: "314 Ogikubo, Odawara, Kanagawa",
      vi: "314 Ogikubo, Odawara, Kanagawa",
    },
    lat: 35.2654570,
    lng: 139.1536560,
    prefecture: "神奈川県",
    area: { ja: "小田原", en: "Odawara", vi: "Odawara" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理",
    price: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
    hours: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
  },
  {
    id: "banh-mi-pate-tsutsumi",
    name: "バインミーパテ ベトナムサンドイッチ 堤店",
    address: {
      ja: "神奈川県茅ヶ崎市堤73-7",
      en: "73-7 Tsutsumi, Chigasaki, Kanagawa",
      vi: "73-7 Tsutsumi, Chigasaki, Kanagawa",
    },
    lat: 35.3674010,
    lng: 139.4334560,
    prefecture: "神奈川県",
    area: { ja: "茅ヶ崎", en: "Chigasaki", vi: "Chigasaki" },
    dishes: ["ベトナム料理"],
    category: "バインミー",
    price: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
    hours: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
  },
  {
    id: "sminhemi-cafe",
    name: "Sminhemi cafe",
    address: {
      ja: "神奈川県茅ヶ崎市行谷1033-1",
      en: "1033-1 Namegaya, Chigasaki, Kanagawa",
      vi: "1033-1 Namegaya, Chigasaki, Kanagawa",
    },
    lat: 35.3701520,
    lng: 139.4189760,
    prefecture: "神奈川県",
    area: { ja: "茅ヶ崎", en: "Chigasaki", vi: "Chigasaki" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理・カフェ",
    price: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
    hours: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
  },
  {
    id: "haimi-sagamihara",
    name: "ハイミ",
    address: {
      ja: "神奈川県相模原市中央区共和3-12-10",
      en: "3-12-10 Kyowa, Chuo-ku, Sagamihara, Kanagawa",
      vi: "3-12-10 Kyowa, Quận Chuo, Sagamihara, Kanagawa",
    },
    lat: 35.5597420,
    lng: 139.4024810,
    prefecture: "神奈川県",
    area: { ja: "淵野辺・共和", en: "Fuchinobe / Kyowa", vi: "Fuchinobe / Kyowa" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理",
    price: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
    hours: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
  },
  {
    id: "pho-hashi-hashimoto",
    name: "フォーはし",
    address: {
      ja: "神奈川県相模原市緑区西橋本5-1-2",
      en: "5-1-2 Nishi-Hashimoto, Midori-ku, Sagamihara, Kanagawa",
      vi: "5-1-2 Nishi-Hashimoto, Quận Midori, Sagamihara, Kanagawa",
    },
    lat: 35.5972330,
    lng: 139.3375240,
    prefecture: "神奈川県",
    area: { ja: "橋本", en: "Hashimoto", vi: "Hashimoto" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理",
    price: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
    hours: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
  },
  {
    id: "oriental-cafe-suiren",
    name: "Oriental Cafe SUIREN",
    address: {
      ja: "神奈川県相模原市南区東大沼3-30-42",
      en: "3-30-42 Higashi-Onuma, Minami-ku, Sagamihara, Kanagawa",
      vi: "3-30-42 Higashi-Onuma, Quận Minami, Sagamihara, Kanagawa",
    },
    lat: 35.5388110,
    lng: 139.4161830,
    prefecture: "神奈川県",
    area: { ja: "東大沼", en: "Higashi-Onuma", vi: "Higashi-Onuma" },
    dishes: ["ベトナム料理"],
    category: "ベトナム料理・カフェ",
    price: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
    hours: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
  },
  {
    id: "pho-sagamihara-station",
    name: "ベトナム料理(フォー専門店)",
    address: {
      ja: "神奈川県相模原市中央区相模原2-2-16",
      en: "2-2-16 Sagamihara, Chuo-ku, Sagamihara, Kanagawa",
      vi: "2-2-16 Sagamihara, Quận Chuo, Sagamihara, Kanagawa",
    },
    lat: 35.5807080,
    lng: 139.3696900,
    prefecture: "神奈川県",
    area: { ja: "相模原駅", en: "Sagamihara Station", vi: "Sagamihara Station" },
    dishes: ["ベトナム料理"],
    category: "フォー専門",
    price: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
    hours: { ja: "準備中", en: "Coming soon", vi: "Sắp cập nhật" },
  },
  // ---- ここから ベトナム食材店(type: "grocery")----
  // ※ 緯度・経度は、国土地理院の住所検索で調べた値です(金田東6丁目のお店は「丁目」までの精度)。
  {
    id: "dung-huyen-shin-matsudo",
    type: "grocery",
    name: "ベトナム食材 ズンフェン (Quan Dung Huyen)",
    address: {
      ja: "千葉県松戸市新松戸1-420",
      en: "1-420 Shin-Matsudo, Matsudo, Chiba",
      vi: "1-420 Shin-Matsudo, Matsudo, Chiba",
    },
    lat: 35.8279800,
    lng: 139.9205170,
    prefecture: "千葉県",
    area: { ja: "新松戸", en: "Shin-Matsudo", vi: "Shin-Matsudo" },
    category: "ベトナム食材店",
  },
  {
    id: "xuan-shop-shin-matsudo",
    type: "grocery",
    name: "XUAN SHOP VIET NHAT 新松戸",
    address: {
      ja: "千葉県松戸市新松戸1-498 コンフォートビル3F",
      en: "Comfort Bldg. 3F, 1-498 Shin-Matsudo, Matsudo, Chiba",
      vi: "Comfort Bldg. 3F, 1-498 Shin-Matsudo, Matsudo, Chiba",
    },
    lat: 35.8265150,
    lng: 139.9201970,
    prefecture: "千葉県",
    area: { ja: "新松戸", en: "Shin-Matsudo", vi: "Shin-Matsudo" },
    category: "ベトナム食材店",
  },
  {
    id: "kien-shop-shin-matsudo",
    type: "grocery",
    name: "Kien Shop / Chợ Việt Chiba",
    address: {
      ja: "千葉県松戸市新松戸3-124-2",
      en: "3-124-2 Shin-Matsudo, Matsudo, Chiba",
      vi: "3-124-2 Shin-Matsudo, Matsudo, Chiba",
    },
    lat: 35.8237080,
    lng: 139.9181980,
    prefecture: "千葉県",
    area: { ja: "新松戸", en: "Shin-Matsudo", vi: "Shin-Matsudo" },
    category: "ベトナム食材店",
  },
  {
    id: "tap-hoa-viet-nhat-funabashi",
    type: "grocery",
    name: "Tap Hoa Viet Nhat",
    address: {
      ja: "千葉県船橋市本町2-16-22",
      en: "2-16-22 Honcho, Funabashi, Chiba",
      vi: "2-16-22 Honcho, Funabashi, Chiba",
    },
    lat: 35.6987690,
    lng: 139.9806210,
    prefecture: "千葉県",
    area: { ja: "船橋駅", en: "Funabashi Station", vi: "Funabashi Station" },
    category: "ベトナム食材店",
  },
  {
    id: "mai-toan-motoyawata",
    type: "grocery",
    name: "Thực Phẩm Việt Mai Toán",
    address: {
      ja: "千葉県市川市南八幡5-3-6 102",
      en: "#102, 5-3-6 Minami-Yawata, Ichikawa, Chiba",
      vi: "#102, 5-3-6 Minami-Yawata, Ichikawa, Chiba",
    },
    lat: 35.7213750,
    lng: 139.9241180,
    prefecture: "千葉県",
    area: { ja: "本八幡", en: "Motoyawata", vi: "Motoyawata" },
    category: "ベトナム食材店",
  },
  {
    id: "hong-nhung-kisarazu",
    type: "grocery",
    name: "Hồng Nhung Quán Tạp Hoá Việt Nam",
    address: {
      ja: "千葉県木更津市金田東6丁目26-5",
      en: "6-26-5 Kaneda-Higashi, Kisarazu, Chiba",
      vi: "6-26-5 Kaneda-Higashi, Kisarazu, Chiba",
    },
    lat: 35.4304810,
    lng: 139.9275510,
    prefecture: "千葉県",
    area: { ja: "木更津・金田", en: "Kisarazu / Kaneda", vi: "Kisarazu / Kaneda" },
    category: "ベトナム食材店",
  },
  {
    id: "tap-hoa-viet-asian-food-kisarazu",
    type: "grocery",
    name: "TAP HOA VIET ASIAN FOOD",
    address: {
      ja: "千葉県木更津市貝渕2丁目10-2",
      en: "2-10-2 Kaibuchi, Kisarazu, Chiba",
      vi: "2-10-2 Kaibuchi, Kisarazu, Chiba",
    },
    lat: 35.3754350,
    lng: 139.9228060,
    prefecture: "千葉県",
    area: { ja: "木更津駅", en: "Kisarazu Station", vi: "Kisarazu Station" },
    category: "ベトナム食材店",
  },
  {
    id: "hai-ban-shop-kisarazu",
    type: "grocery",
    name: "ハイバンショップ",
    address: {
      ja: "千葉県木更津市東中央1丁目1-2 102",
      en: "#102, 1-1-2 Higashi-Chuo, Kisarazu, Chiba",
      vi: "#102, 1-1-2 Higashi-Chuo, Kisarazu, Chiba",
    },
    lat: 35.3821600,
    lng: 139.9269260,
    prefecture: "千葉県",
    area: { ja: "木更津駅", en: "Kisarazu Station", vi: "Kisarazu Station" },
    category: "ベトナム食材店",
  },
  // ---- ベトナム食材店(東京都)----
  // ※ 緯度・経度は、国土地理院の住所検索で調べた値です(武蔵野台1-3-9 は「3番」まで、東日暮里5-43 は「43番」までの精度)。
  {
    id: "xuan-shop-omori",
    type: "grocery",
    name: "スァン・ショップ・ベトニャット",
    address: {
      ja: "東京都大田区大森北1-26-6 尾上ビル1F",
      en: "Onoe Bldg. 1F, 1-26-6 Omori-Kita, Ota-ku, Tokyo",
      vi: "Onoe Bldg. 1F, 1-26-6 Omori-Kita, Ota-ku, Tokyo",
    },
    lat: 35.5849990,
    lng: 139.7298280,
    prefecture: "東京都",
    area: { ja: "大森", en: "Omori", vi: "Omori" },
    category: "ベトナム食材店",
  },
  {
    id: "vietcook-kamata",
    type: "grocery",
    name: "Vietcook Kamata",
    address: {
      ja: "東京都大田区西蒲田7-48-14 蒲田センタービル1F",
      en: "Kamata Center Bldg. 1F, 7-48-14 Nishi-Kamata, Ota-ku, Tokyo",
      vi: "Kamata Center Bldg. 1F, 7-48-14 Nishi-Kamata, Ota-ku, Tokyo",
    },
    lat: 35.5623400,
    lng: 139.7135470,
    prefecture: "東京都",
    area: { ja: "蒲田", en: "Kamata", vi: "Kamata" },
    category: "ベトナム食材店",
  },
  {
    id: "green-plus-negishi",
    type: "grocery",
    name: "Green Plus - Cửa hàng bánh mì, thực phẩm Việt Nam",
    address: {
      ja: "東京都台東区根岸2-12-5",
      en: "2-12-5 Negishi, Taito-ku, Tokyo",
      vi: "2-12-5 Negishi, Taito-ku, Tokyo",
    },
    lat: 35.7245980,
    lng: 139.7771760,
    prefecture: "東京都",
    area: { ja: "鶯谷・根岸", en: "Uguisudani / Negishi", vi: "Uguisudani / Negishi" },
    category: "ベトナム食材店",
  },
  {
    id: "cho-viet-okubo",
    type: "grocery",
    name: "Cho Viet Okubo",
    address: {
      ja: "東京都新宿区百人町2-26-6",
      en: "2-26-6 Hyakunincho, Shinjuku-ku, Tokyo",
      vi: "2-26-6 Hyakunincho, Shinjuku-ku, Tokyo",
    },
    lat: 35.7036930,
    lng: 139.6949620,
    prefecture: "東京都",
    area: { ja: "新大久保", en: "Shin-Okubo", vi: "Shin-Okubo" },
    category: "ベトナム食材店",
  },
  {
    id: "vietcook-shinokubo",
    type: "grocery",
    name: "Vietcook Shinokubo",
    address: {
      ja: "東京都新宿区百人町1-17-10 S.Tビル102",
      en: "S.T Bldg. #102, 1-17-10 Hyakunincho, Shinjuku-ku, Tokyo",
      vi: "S.T Bldg. #102, 1-17-10 Hyakunincho, Shinjuku-ku, Tokyo",
    },
    lat: 35.7015690,
    lng: 139.6980900,
    prefecture: "東京都",
    area: { ja: "新大久保", en: "Shin-Okubo", vi: "Shin-Okubo" },
    category: "ベトナム食材店",
  },
  {
    id: "xuan-shop-ikebukuro",
    type: "grocery",
    name: "Xuân shop Việt Nhật Ikebukuro",
    address: {
      ja: "東京都豊島区池袋2-58-5 1C",
      en: "#1C, 2-58-5 Ikebukuro, Toshima-ku, Tokyo",
      vi: "#1C, 2-58-5 Ikebukuro, Toshima-ku, Tokyo",
    },
    lat: 35.7349740,
    lng: 139.7084960,
    prefecture: "東京都",
    area: { ja: "池袋", en: "Ikebukuro", vi: "Ikebukuro" },
    category: "ベトナム食材店",
  },
  {
    id: "cho-viet-sugamo-3s",
    type: "grocery",
    name: "Chợ Việt Sugamo 3S",
    address: {
      ja: "東京都豊島区巣鴨1-18-13",
      en: "1-18-13 Sugamo, Toshima-ku, Tokyo",
      vi: "1-18-13 Sugamo, Toshima-ku, Tokyo",
    },
    lat: 35.7320590,
    lng: 139.7395940,
    prefecture: "東京都",
    area: { ja: "巣鴨", en: "Sugamo", vi: "Sugamo" },
    category: "ベトナム食材店",
  },
  {
    id: "viet-foods-otsuka",
    type: "grocery",
    name: "VIET FOODS OTSUKA",
    address: {
      ja: "東京都豊島区南大塚3-52-1 俊川ビル2F",
      en: "Shunkawa Bldg. 2F, 3-52-1 Minami-Otsuka, Toshima-ku, Tokyo",
      vi: "Shunkawa Bldg. 2F, 3-52-1 Minami-Otsuka, Toshima-ku, Tokyo",
    },
    lat: 35.7299270,
    lng: 139.7288670,
    prefecture: "東京都",
    area: { ja: "大塚", en: "Otsuka", vi: "Otsuka" },
    category: "ベトナム食材店",
  },
  {
    id: "cho-viet-nippori",
    type: "grocery",
    name: "Chợ Việt Nippori",
    address: {
      ja: "東京都荒川区西日暮里2-21-4 クレスト秋山",
      en: "Crest Akiyama, 2-21-4 Nishi-Nippori, Arakawa-ku, Tokyo",
      vi: "Crest Akiyama, 2-21-4 Nishi-Nippori, Arakawa-ku, Tokyo",
    },
    lat: 35.7293360,
    lng: 139.7700650,
    prefecture: "東京都",
    area: { ja: "日暮里", en: "Nippori", vi: "Nippori" },
    category: "ベトナム食材店",
  },
  {
    id: "xuan-shop-nishi-nippori",
    type: "grocery",
    name: "Xuân shop Việt Nhật Nishi Nippori",
    address: {
      ja: "東京都荒川区西日暮里4-1-18 第一近藤ビル101",
      en: "Daiichi Kondo Bldg. #101, 4-1-18 Nishi-Nippori, Arakawa-ku, Tokyo",
      vi: "Daiichi Kondo Bldg. #101, 4-1-18 Nishi-Nippori, Arakawa-ku, Tokyo",
    },
    lat: 35.7327730,
    lng: 139.7660060,
    prefecture: "東京都",
    area: { ja: "日暮里", en: "Nippori", vi: "Nippori" },
    category: "ベトナム食材店",
  },
  {
    id: "star-shop-higashi-nippori",
    type: "grocery",
    name: "ベトナム食品館 Star Shop",
    address: {
      ja: "東京都荒川区東日暮里5-43",
      en: "5-43 Higashi-Nippori, Arakawa-ku, Tokyo",
      vi: "5-43 Higashi-Nippori, Arakawa-ku, Tokyo",
    },
    lat: 35.7276080,
    lng: 139.7744140,
    prefecture: "東京都",
    area: { ja: "日暮里", en: "Nippori", vi: "Nippori" },
    category: "ベトナム食材店",
  },
  {
    id: "vietnam-shop-asia-matsushima",
    type: "grocery",
    name: "ベトナムショップ アジア",
    address: {
      ja: "東京都江戸川区松島3-29-12",
      en: "3-29-12 Matsushima, Edogawa-ku, Tokyo",
      vi: "3-29-12 Matsushima, Edogawa-ku, Tokyo",
    },
    lat: 35.7123030,
    lng: 139.8630520,
    prefecture: "東京都",
    area: { ja: "新小岩", en: "Shin-Koiwa", vi: "Shin-Koiwa" },
    category: "ベトナム食材店",
  },
  {
    id: "susu-quan-mikawashima",
    type: "grocery",
    name: "SuSu Quán 三河島 日暮里",
    address: {
      ja: "東京都荒川区荒川3-64-3",
      en: "3-64-3 Arakawa, Arakawa-ku, Tokyo",
      vi: "3-64-3 Arakawa, Arakawa-ku, Tokyo",
    },
    lat: 35.7343440,
    lng: 139.7790370,
    prefecture: "東京都",
    area: { ja: "三河島", en: "Mikawashima", vi: "Mikawashima" },
    category: "ベトナム食材店",
  },
  {
    id: "huong-viet-mart-ayase",
    type: "grocery",
    name: "HUONG VIET MART AYASE",
    address: {
      ja: "東京都葛飾区小菅4-12-3",
      en: "4-12-3 Kosuge, Katsushika-ku, Tokyo",
      vi: "4-12-3 Kosuge, Katsushika-ku, Tokyo",
    },
    lat: 35.7620890,
    lng: 139.8265840,
    prefecture: "東京都",
    area: { ja: "綾瀬・小菅", en: "Ayase / Kosuge", vi: "Ayase / Kosuge" },
    category: "ベトナム食材店",
  },
  {
    id: "cho-viet-ohanajaya",
    type: "grocery",
    name: "Chợ Việt Ohanajaya",
    address: {
      ja: "東京都葛飾区お花茶屋1-16-10 お花茶屋ビル202",
      en: "Ohanajaya Bldg. #202, 1-16-10 Ohanajaya, Katsushika-ku, Tokyo",
      vi: "Ohanajaya Bldg. #202, 1-16-10 Ohanajaya, Katsushika-ku, Tokyo",
    },
    lat: 35.7485810,
    lng: 139.8396450,
    prefecture: "東京都",
    area: { ja: "お花茶屋", en: "Ohanajaya", vi: "Ohanajaya" },
    category: "ベトナム食材店",
  },
  {
    id: "happy-mart-takenotsuka",
    type: "grocery",
    name: "Happy mart siêu thị Việt",
    address: {
      ja: "東京都足立区竹の塚6-11-12 八汐ビル201",
      en: "Yashio Bldg. #201, 6-11-12 Takenotsuka, Adachi-ku, Tokyo",
      vi: "Yashio Bldg. #201, 6-11-12 Takenotsuka, Adachi-ku, Tokyo",
    },
    lat: 35.7948190,
    lng: 139.7944790,
    prefecture: "東京都",
    area: { ja: "竹ノ塚", en: "Takenotsuka", vi: "Takenotsuka" },
    category: "ベトナム食材店",
  },
  {
    id: "tt-group-viet-mart-takenotsuka",
    type: "grocery",
    name: "TT GROUP VIET MART",
    address: {
      ja: "東京都足立区竹の塚2-23-8 101",
      en: "#101, 2-23-8 Takenotsuka, Adachi-ku, Tokyo",
      vi: "#101, 2-23-8 Takenotsuka, Adachi-ku, Tokyo",
    },
    lat: 35.7911110,
    lng: 139.7942660,
    prefecture: "東京都",
    area: { ja: "竹ノ塚", en: "Takenotsuka", vi: "Takenotsuka" },
    category: "ベトナム食材店",
  },
  {
    id: "gold-time-mart-nakano",
    type: "grocery",
    name: "GOLD TIME MART",
    address: {
      ja: "東京都中野区中野3-32-10 アヤベビル302",
      en: "Ayabe Bldg. #302, 3-32-10 Nakano, Nakano-ku, Tokyo",
      vi: "Ayabe Bldg. #302, 3-32-10 Nakano, Nakano-ku, Tokyo",
    },
    lat: 35.7029190,
    lng: 139.6650240,
    prefecture: "東京都",
    area: { ja: "中野", en: "Nakano", vi: "Nakano" },
    category: "ベトナム食材店",
  },
  {
    id: "cho-viet-machida",
    type: "grocery",
    name: "CHỢ VIỆT MACHIDA",
    address: {
      ja: "東京都町田市原町田1-9-16",
      en: "1-9-16 Haramachida, Machida, Tokyo",
      vi: "1-9-16 Haramachida, Machida, Tokyo",
    },
    lat: 35.5391080,
    lng: 139.4483640,
    prefecture: "東京都",
    area: { ja: "町田", en: "Machida", vi: "Machida" },
    category: "ベトナム食材店",
  },
  {
    id: "tap-hoa-nana-fussa",
    type: "grocery",
    name: "TAP HOA NANA ベトナムの食品館",
    address: {
      ja: "東京都福生市武蔵野台1-3-9",
      en: "1-3-9 Musashinodai, Fussa, Tokyo",
      vi: "1-3-9 Musashinodai, Fussa, Tokyo",
    },
    lat: 35.7454340,
    lng: 139.3350070,
    prefecture: "東京都",
    area: { ja: "福生", en: "Fussa", vi: "Fussa" },
    category: "ベトナム食材店",
  },
  {
    id: "xuan-shop-fussa",
    type: "grocery",
    name: "XUÂN SHOP VIỆT NHẬT FUSSA",
    address: {
      ja: "東京都福生市福生768",
      en: "768 Fussa, Fussa, Tokyo",
      vi: "768 Fussa, Fussa, Tokyo",
    },
    lat: 35.7420160,
    lng: 139.3273320,
    prefecture: "東京都",
    area: { ja: "福生", en: "Fussa", vi: "Fussa" },
    category: "ベトナム食材店",
  },
  {
    id: "vietcook-fussa",
    type: "grocery",
    name: "Vietcook Fussa",
    address: {
      ja: "東京都福生市東町15-1",
      en: "15-1 Higashicho, Fussa, Tokyo",
      vi: "15-1 Higashicho, Fussa, Tokyo",
    },
    lat: 35.7457240,
    lng: 139.3264920,
    prefecture: "東京都",
    area: { ja: "福生", en: "Fussa", vi: "Fussa" },
    category: "ベトナム食材店",
  },
  // ---- ベトナム食材店(神奈川県)----
  // ※ 緯度・経度は、国土地理院の住所検索で調べた値です。
  //   川崎区の4件・長者町・福富町・初音町・宮川町は「番」まで、愛川町中津は「中津」の中心(正確な位置は要確認)の精度です。
  {
    id: "vietcook-yokohama",
    type: "grocery",
    name: "ベトクック横浜",
    address: {
      ja: "神奈川県横浜市中区長者町8-133-1",
      en: "8-133-1 Chojamachi, Naka-ku, Yokohama, Kanagawa",
      vi: "8-133-1 Chojamachi, Naka-ku, Yokohama, Kanagawa",
    },
    lat: 35.4441110,
    lng: 139.6299440,
    prefecture: "神奈川県",
    area: { ja: "伊勢佐木町", en: "Isezakicho", vi: "Isezakicho" },
    category: "ベトナム食材店",
  },
  {
    id: "xuan-shop-yokohama",
    type: "grocery",
    name: "Xuân Shop Việt Nhật - Yokohama",
    address: {
      ja: "神奈川県横浜市中区福富町西通45-1 ファーストビル1F",
      en: "First Bldg. 1F, 45-1 Fukutomicho-Nishidori, Naka-ku, Yokohama, Kanagawa",
      vi: "First Bldg. 1F, 45-1 Fukutomicho-Nishidori, Naka-ku, Yokohama, Kanagawa",
    },
    lat: 35.4456630,
    lng: 139.6294100,
    prefecture: "神奈川県",
    area: { ja: "福富町", en: "Fukutomicho", vi: "Fukutomicho" },
    category: "ベトナム食材店",
  },
  {
    id: "bamboo-store-hatsunecho",
    type: "grocery",
    name: "BAMBOO STORE",
    address: {
      ja: "神奈川県横浜市中区初音町1-2-16",
      en: "1-2-16 Hatsunecho, Naka-ku, Yokohama, Kanagawa",
      vi: "1-2-16 Hatsunecho, Naka-ku, Yokohama, Kanagawa",
    },
    lat: 35.4421840,
    lng: 139.6250000,
    prefecture: "神奈川県",
    area: { ja: "阪東橋", en: "Bandobashi", vi: "Bandobashi" },
    category: "ベトナム食材店",
  },
  {
    id: "huong-vi-viet-miyagawacho",
    type: "grocery",
    name: "HUONG VI VIET",
    address: {
      ja: "神奈川県横浜市中区宮川町3-88-3",
      en: "3-88-3 Miyagawacho, Naka-ku, Yokohama, Kanagawa",
      vi: "3-88-3 Miyagawacho, Naka-ku, Yokohama, Kanagawa",
    },
    lat: 35.4469950,
    lng: 139.6269070,
    prefecture: "神奈川県",
    area: { ja: "日ノ出町", en: "Hinodecho", vi: "Hinodecho" },
    category: "ベトナム食材店",
  },
  {
    id: "xuan-shop-kawasaki",
    type: "grocery",
    name: "XUÂN SHOP VIỆT NHẬT KAWASAKI",
    address: {
      ja: "神奈川県川崎市川崎区南町15-3 日神パレステージ川崎102",
      en: "Nisshin Palacestage Kawasaki #102, 15-3 Minamicho, Kawasaki-ku, Kawasaki, Kanagawa",
      vi: "Nisshin Palacestage Kawasaki #102, 15-3 Minamicho, Kawasaki-ku, Kawasaki, Kanagawa",
    },
    lat: 35.5266150,
    lng: 139.7004390,
    prefecture: "神奈川県",
    area: { ja: "川崎駅", en: "Kawasaki Station", vi: "Kawasaki Station" },
    category: "ベトナム食材店",
  },
  {
    id: "vietcook-daishi",
    type: "grocery",
    name: "Vietcook Daishi",
    address: {
      ja: "神奈川県川崎市川崎区台町6-10-1",
      en: "6-10-1 Daimachi, Kawasaki-ku, Kawasaki, Kanagawa",
      vi: "6-10-1 Daimachi, Kawasaki-ku, Kawasaki, Kanagawa",
    },
    lat: 35.5295750,
    lng: 139.7332760,
    prefecture: "神奈川県",
    area: { ja: "川崎大師", en: "Kawasaki Daishi", vi: "Kawasaki Daishi" },
    category: "ベトナム食材店",
  },
  {
    id: "mart-viet-foods-kawasaki",
    type: "grocery",
    name: "Mart Việt Foods Kawasaki",
    address: {
      ja: "神奈川県川崎市川崎区中島3-7-1 2F",
      en: "2F, 3-7-1 Nakajima, Kawasaki-ku, Kawasaki, Kanagawa",
      vi: "2F, 3-7-1 Nakajima, Kawasaki-ku, Kawasaki, Kanagawa",
    },
    lat: 35.5265850,
    lng: 139.7166600,
    prefecture: "神奈川県",
    area: { ja: "川崎・中島", en: "Kawasaki / Nakajima", vi: "Kawasaki / Nakajima" },
    category: "ベトナム食材店",
  },
  {
    id: "asian-food-store-kawasaki",
    type: "grocery",
    name: "ASIAN FOOD STORE KAWASAKI - QUÁN VIỆT",
    address: {
      ja: "神奈川県川崎市川崎区小川町17-4 川商ビル1F",
      en: "Kawasho Bldg. 1F, 17-4 Ogawacho, Kawasaki-ku, Kawasaki, Kanagawa",
      vi: "Kawasho Bldg. 1F, 17-4 Ogawacho, Kawasaki-ku, Kawasaki, Kanagawa",
    },
    lat: 35.5268170,
    lng: 139.6982570,
    prefecture: "神奈川県",
    area: { ja: "川崎駅", en: "Kawasaki Station", vi: "Kawasaki Station" },
    category: "ベトナム食材店",
  },
  {
    id: "xuan-shop-hashimoto",
    type: "grocery",
    name: "XUÂN SHOP VIỆT NHẬT - HASHIMOTO",
    address: {
      ja: "神奈川県相模原市中央区南橋本2-6-16",
      en: "2-6-16 Minami-Hashimoto, Chuo-ku, Sagamihara, Kanagawa",
      vi: "2-6-16 Minami-Hashimoto, Chuo-ku, Sagamihara, Kanagawa",
    },
    lat: 35.5811200,
    lng: 139.3509370,
    prefecture: "神奈川県",
    area: { ja: "橋本", en: "Hashimoto", vi: "Hashimoto" },
    category: "ベトナム食材店",
  },
  {
    id: "yen-shop-hashimoto",
    type: "grocery",
    name: "YEN SHOP - THE GIOI DO VIET 橋本店",
    address: {
      ja: "神奈川県相模原市緑区東橋本3-16-8 ライフプラザカナン1F",
      en: "Life Plaza Kanan 1F, 3-16-8 Higashi-Hashimoto, Midori-ku, Sagamihara, Kanagawa",
      vi: "Life Plaza Kanan 1F, 3-16-8 Higashi-Hashimoto, Midori-ku, Sagamihara, Kanagawa",
    },
    lat: 35.5960460,
    lng: 139.3532710,
    prefecture: "神奈川県",
    area: { ja: "橋本", en: "Hashimoto", vi: "Hashimoto" },
    category: "ベトナム食材店",
  },
  {
    id: "the-gioi-do-viet-kamimizo",
    type: "grocery",
    name: "The Gioi Do Viet Kamimizo",
    address: {
      ja: "神奈川県相模原市中央区上溝5-14-6 海寶ビル1F",
      en: "Kaiho Bldg. 1F, 5-14-6 Kamimizo, Chuo-ku, Sagamihara, Kanagawa",
      vi: "Kaiho Bldg. 1F, 5-14-6 Kamimizo, Chuo-ku, Sagamihara, Kanagawa",
    },
    lat: 35.5578770,
    lng: 139.3620000,
    prefecture: "神奈川県",
    area: { ja: "上溝", en: "Kamimizo", vi: "Kamimizo" },
    category: "ベトナム食材店",
  },
  {
    id: "cho-viet-isehara",
    type: "grocery",
    name: "CHỢ VIỆT Isehara",
    address: {
      ja: "神奈川県伊勢原市伊勢原1-33-17 駒形ビル1F",
      en: "Komagata Bldg. 1F, 1-33-17 Isehara, Isehara, Kanagawa",
      vi: "Komagata Bldg. 1F, 1-33-17 Isehara, Isehara, Kanagawa",
    },
    lat: 35.3987690,
    lng: 139.3185730,
    prefecture: "神奈川県",
    area: { ja: "伊勢原", en: "Isehara", vi: "Isehara" },
    category: "ベトナム食材店",
  },
  {
    id: "vietnam-grocery-sagami-ono",
    type: "grocery",
    name: "ベトナム食材店(相模大野)",
    address: {
      ja: "神奈川県相模原市南区相模大野6-13-10 201",
      en: "#201, 6-13-10 Sagami-Ono, Minami-ku, Sagamihara, Kanagawa",
      vi: "#201, 6-13-10 Sagami-Ono, Minami-ku, Sagamihara, Kanagawa",
    },
    lat: 35.5299760,
    lng: 139.4331970,
    prefecture: "神奈川県",
    area: { ja: "相模大野", en: "Sagami-Ono", vi: "Sagami-Ono" },
    category: "ベトナム食材店",
  },
  {
    id: "vietcook-honatsugi",
    type: "grocery",
    name: "Vietcook Honatsugi",
    address: {
      ja: "神奈川県厚木市中町4-6-11 山口ビル101",
      en: "Yamaguchi Bldg. #101, 4-6-11 Nakacho, Atsugi, Kanagawa",
      vi: "Yamaguchi Bldg. #101, 4-6-11 Nakacho, Atsugi, Kanagawa",
    },
    lat: 35.4372290,
    lng: 139.3613890,
    prefecture: "神奈川県",
    area: { ja: "本厚木", en: "Hon-Atsugi", vi: "Hon-Atsugi" },
    category: "ベトナム食材店",
  },
  {
    id: "vinafood-aikoishida",
    type: "grocery",
    name: "Vinafood Aikoishida",
    address: {
      ja: "神奈川県厚木市愛甲4-1-9",
      en: "4-1-9 Aiko, Atsugi, Kanagawa",
      vi: "4-1-9 Aiko, Atsugi, Kanagawa",
    },
    lat: 35.4210210,
    lng: 139.3410640,
    prefecture: "神奈川県",
    area: { ja: "愛甲石田", en: "Aiko-Ishida", vi: "Aiko-Ishida" },
    category: "ベトナム食材店",
  },
  {
    id: "cho-viet-hadano",
    type: "grocery",
    name: "Chợ Việt Hadano",
    address: {
      ja: "神奈川県秦野市本町1-1-11",
      en: "1-1-11 Honcho, Hadano, Kanagawa",
      vi: "1-1-11 Honcho, Hadano, Kanagawa",
    },
    lat: 35.3722840,
    lng: 139.2254180,
    prefecture: "神奈川県",
    area: { ja: "秦野", en: "Hadano", vi: "Hadano" },
    category: "ベトナム食材店",
  },
  {
    id: "cho-viet-aikogun",
    type: "grocery",
    name: "Chợ Việt Aikogun",
    address: {
      ja: "神奈川県愛甲郡愛川町中津210-1 オーク中津2F",
      en: "Oak Nakatsu 2F, 210-1 Nakatsu, Aikawa, Aiko-gun, Kanagawa",
      vi: "Oak Nakatsu 2F, 210-1 Nakatsu, Aikawa, Aiko-gun, Kanagawa",
    },
    lat: 35.5170480,
    lng: 139.3369450,
    prefecture: "神奈川県",
    area: { ja: "愛川・中津", en: "Aikawa / Nakatsu", vi: "Aikawa / Nakatsu" },
    category: "ベトナム食材店",
  },
  // ---- ベトナム食材店(埼玉県)----
  // ※ 緯度・経度は、国土地理院の住所検索で調べた値です。
  //   安行領根岸(SaigonJP)と下戸田(The Foods)は地区の中心付近で、正確な位置は要確認です。
  //   采女1-90・1-91 の2件は、同じ場所として出たため、ピンが重なります。
  {
    id: "vietcook-omiya",
    type: "grocery",
    name: "Vietcook Omiya",
    address: {
      ja: "埼玉県さいたま市大宮区錦町3973-5",
      en: "3973-5 Nishikicho, Omiya-ku, Saitama, Saitama",
      vi: "3973-5 Nishikicho, Omiya-ku, Saitama, Saitama",
    },
    lat: 35.9042890,
    lng: 139.6240690,
    prefecture: "埼玉県",
    area: { ja: "大宮", en: "Omiya", vi: "Omiya" },
    category: "ベトナム食材店",
  },
  {
    id: "sieu-thi-viet-omiya",
    type: "grocery",
    name: "Siêu Thị Việt Omiya",
    address: {
      ja: "埼玉県さいたま市見沼区東大宮5-6-1",
      en: "5-6-1 Higashi-Omiya, Minuma-ku, Saitama, Saitama",
      vi: "5-6-1 Higashi-Omiya, Minuma-ku, Saitama, Saitama",
    },
    lat: 35.9469720,
    lng: 139.6401210,
    prefecture: "埼玉県",
    area: { ja: "東大宮", en: "Higashi-Omiya", vi: "Higashi-Omiya" },
    category: "ベトナム食材店",
  },
  {
    id: "cho-viet-sakura",
    type: "grocery",
    name: "CHỢ VIỆT SAKURA",
    address: {
      ja: "埼玉県さいたま市桜区道場2-15-11",
      en: "2-15-11 Dojo, Sakura-ku, Saitama, Saitama",
      vi: "2-15-11 Dojo, Sakura-ku, Saitama, Saitama",
    },
    lat: 35.8579060,
    lng: 139.6112520,
    prefecture: "埼玉県",
    area: { ja: "桜区・道場", en: "Sakura-ku / Dojo", vi: "Sakura-ku / Dojo" },
    category: "ベトナム食材店",
  },
  {
    id: "xuan-shop-nishikawaguchi",
    type: "grocery",
    name: "Xuân shop Nishikawaguchi Cửa Tây",
    address: {
      ja: "埼玉県川口市西川口1-22-15 三恵ビル1F E",
      en: "Sankei Bldg. 1F-E, 1-22-15 Nishi-Kawaguchi, Kawaguchi, Saitama",
      vi: "Sankei Bldg. 1F-E, 1-22-15 Nishi-Kawaguchi, Kawaguchi, Saitama",
    },
    lat: 35.8144530,
    lng: 139.7026370,
    prefecture: "埼玉県",
    area: { ja: "西川口", en: "Nishi-Kawaguchi", vi: "Nishi-Kawaguchi" },
    category: "ベトナム食材店",
  },
  {
    id: "saigonjp-kawaguchi",
    type: "grocery",
    name: "SaigonJP Thực Phẩm",
    address: {
      ja: "埼玉県川口市安行領根岸5449-1",
      en: "5449-1 Angyoryo-Negishi, Kawaguchi, Saitama",
      vi: "5449-1 Angyoryo-Negishi, Kawaguchi, Saitama",
    },
    lat: 35.8437310,
    lng: 139.7180940,
    prefecture: "埼玉県",
    area: { ja: "川口・安行", en: "Kawaguchi / Angyo", vi: "Kawaguchi / Angyo" },
    category: "ベトナム食材店",
  },
  {
    id: "xuan-shop-soka",
    type: "grocery",
    name: "Xuân shop Việt Nhật Soka",
    address: {
      ja: "埼玉県草加市氷川町2111-13",
      en: "2111-13 Hikawacho, Soka, Saitama",
      vi: "2111-13 Hikawacho, Soka, Saitama",
    },
    lat: 35.8285600,
    lng: 139.7989960,
    prefecture: "埼玉県",
    area: { ja: "草加", en: "Soka", vi: "Soka" },
    category: "ベトナム食材店",
  },
  {
    id: "thai-binh-food-soka",
    type: "grocery",
    name: "THÁI BÌNH food",
    address: {
      ja: "埼玉県草加市神明2-3-5 リレントクイーン草加101",
      en: "Relent Queen Soka #101, 2-3-5 Shinmei, Soka, Saitama",
      vi: "Relent Queen Soka #101, 2-3-5 Shinmei, Soka, Saitama",
    },
    lat: 35.8345180,
    lng: 139.8076170,
    prefecture: "埼玉県",
    area: { ja: "草加", en: "Soka", vi: "Soka" },
    category: "ベトナム食材店",
  },
  {
    id: "sovaen-jp-misato",
    type: "grocery",
    name: "Sovaen JP Chợ Việt (ゾバエンジェーピー)",
    address: {
      ja: "埼玉県三郷市采女1-90-2 千代田ビル2F",
      en: "Chiyoda Bldg. 2F, 1-90-2 Uneme, Misato, Saitama",
      vi: "Chiyoda Bldg. 2F, 1-90-2 Uneme, Misato, Saitama",
    },
    lat: 35.8568840,
    lng: 139.8626400,
    prefecture: "埼玉県",
    area: { ja: "新三郷", en: "Shin-Misato", vi: "Shin-Misato" },
    category: "ベトナム食材店",
  },
  {
    id: "vietcook-shimmisato",
    type: "grocery",
    name: "Vietcook Shimmisato",
    address: {
      ja: "埼玉県三郷市采女1-91",
      en: "1-91 Uneme, Misato, Saitama",
      vi: "1-91 Uneme, Misato, Saitama",
    },
    lat: 35.8568840,
    lng: 139.8626400,
    prefecture: "埼玉県",
    area: { ja: "新三郷", en: "Shin-Misato", vi: "Shin-Misato" },
    category: "ベトナム食材店",
  },
  {
    id: "vietnam-super-misato",
    type: "grocery",
    name: "ベトナムスーパー MISATO",
    address: {
      ja: "埼玉県三郷市三郷3-13-3",
      en: "3-13-3 Misato, Misato, Saitama",
      vi: "3-13-3 Misato, Misato, Saitama",
    },
    lat: 35.8457030,
    lng: 139.8807070,
    prefecture: "埼玉県",
    area: { ja: "三郷", en: "Misato", vi: "Misato" },
    category: "ベトナム食材店",
  },
  {
    id: "xuan-shop-yoshikawa",
    type: "grocery",
    name: "XUÂN SHOP VIỆT NHẬT YOSHIKAWA",
    address: {
      ja: "埼玉県吉川市木売2-14-7 ロイヤルメゾン戸張105",
      en: "Royal Maison Tobari #105, 2-14-7 Kiuri, Yoshikawa, Saitama",
      vi: "Royal Maison Tobari #105, 2-14-7 Kiuri, Yoshikawa, Saitama",
    },
    lat: 35.8743740,
    lng: 139.8423610,
    prefecture: "埼玉県",
    area: { ja: "吉川", en: "Yoshikawa", vi: "Yoshikawa" },
    category: "ベトナム食材店",
  },
  {
    id: "cho-viet-wakaba",
    type: "grocery",
    name: "CHỢ VIỆT WAKABA",
    address: {
      ja: "埼玉県鶴ヶ島市富士見1-7-12",
      en: "1-7-12 Fujimi, Tsurugashima, Saitama",
      vi: "1-7-12 Fujimi, Tsurugashima, Saitama",
    },
    lat: 35.9486390,
    lng: 139.4104770,
    prefecture: "埼玉県",
    area: { ja: "若葉", en: "Wakaba", vi: "Wakaba" },
    category: "ベトナム食材店",
  },
  {
    id: "cho-viet-dha-kitamoto",
    type: "grocery",
    name: "Chợ Việt D.H.A 北本",
    address: {
      ja: "埼玉県北本市北本2-26-3 小川ビル1F",
      en: "Ogawa Bldg. 1F, 2-26-3 Kitamoto, Kitamoto, Saitama",
      vi: "Ogawa Bldg. 1F, 2-26-3 Kitamoto, Kitamoto, Saitama",
    },
    lat: 36.0325810,
    lng: 139.5363460,
    prefecture: "埼玉県",
    area: { ja: "北本", en: "Kitamoto", vi: "Kitamoto" },
    category: "ベトナム食材店",
  },
  {
    id: "quan-viet-hanyu",
    type: "grocery",
    name: "Quán Việt Hanyu",
    address: {
      ja: "埼玉県羽生市東6-7-15",
      en: "6-7-15 Higashi, Hanyu, Saitama",
      vi: "6-7-15 Higashi, Hanyu, Saitama",
    },
    lat: 36.1735080,
    lng: 139.5467680,
    prefecture: "埼玉県",
    area: { ja: "羽生", en: "Hanyu", vi: "Hanyu" },
    category: "ベトナム食材店",
  },
  {
    id: "nghe-tinh-shop-warabi",
    type: "grocery",
    name: "Nghệ Tĩnh Shop",
    address: {
      ja: "埼玉県蕨市南町3-18-3 共栄ビル101",
      en: "Kyoei Bldg. #101, 3-18-3 Minamicho, Warabi, Saitama",
      vi: "Kyoei Bldg. #101, 3-18-3 Minamicho, Warabi, Saitama",
    },
    lat: 35.8161890,
    lng: 139.7000430,
    prefecture: "埼玉県",
    area: { ja: "蕨", en: "Warabi", vi: "Warabi" },
    category: "ベトナム食材店",
  },
  {
    id: "the-foods-toda",
    type: "grocery",
    name: "The Foods",
    address: {
      ja: "埼玉県戸田市下戸田745-1-21",
      en: "745-1-21 Shimo-Toda, Toda, Saitama",
      vi: "745-1-21 Shimo-Toda, Toda, Saitama",
    },
    lat: 35.8136630,
    lng: 139.6862640,
    prefecture: "埼玉県",
    area: { ja: "戸田", en: "Toda", vi: "Toda" },
    category: "ベトナム食材店",
  },
  {
    id: "cho-viet-trau-vang-kawagoe",
    type: "grocery",
    name: "CHỢ VIỆT TRÂU VÀNG",
    address: {
      ja: "埼玉県川越市菅原町6-1",
      en: "6-1 Sugaharacho, Kawagoe, Saitama",
      vi: "6-1 Sugaharacho, Kawagoe, Saitama",
    },
    lat: 35.9068910,
    lng: 139.4871220,
    prefecture: "埼玉県",
    area: { ja: "川越", en: "Kawagoe", vi: "Kawagoe" },
    category: "ベトナム食材店",
  },
  {
    id: "xuan-shop-kawagoe",
    type: "grocery",
    name: "Xuân Shop Việt Nhật Kawagoe",
    address: {
      ja: "埼玉県川越市南台3-1-17 南台レジデンス101",
      en: "Minamidai Residence #101, 3-1-17 Minamidai, Kawagoe, Saitama",
      vi: "Minamidai Residence #101, 3-1-17 Minamidai, Kawagoe, Saitama",
    },
    lat: 35.8884930,
    lng: 139.4531860,
    prefecture: "埼玉県",
    area: { ja: "川越", en: "Kawagoe", vi: "Kawagoe" },
    category: "ベトナム食材店",
  },
];
